/**
 * Dynamically load a namespace translation file
 *
 * @param namespace - The namespace to load (e.g., "home", "common")
 * @param lang - The language code (e.g., "ko", "en")
 * @returns The translation data for the specified namespace and language
 */
export async function loadNamespace(namespace: string, lang: string) {
  const module = await import(`./${namespace}/${lang}.json`);
  return module.default;
}

/**
 * Type definitions are automatically generated by i18n-extractor
 * Location: ./types/i18nexus.d.ts
 *
 * To regenerate types, run:
 * ```bash
 * npx i18n-extractor
 * ```
 *
 * Usage in your app:
 * ```typescript
 * import { I18nProvider } from "i18nexus";
 * import { loadNamespace } from "./locales";
 *
 * <I18nProvider
 *   loadNamespace={loadNamespace}
 *   initialLanguage={language}
 *   fallbackNamespace="common"
 *   languageManagerOptions={{...}}
 * >
 *   {children}
 * </I18nProvider>
 * ```
 */
