/* eslint-disable */
/**
 * Auto-generated TypeScript type definitions for i18nexus
 *
 * DO NOT EDIT THIS FILE MANUALLY!
 * Run 'npx i18n-type' to regenerate.
 *
 * @generated by i18nexus-tools
 */

// ============================================
// Global Translation Types
// ============================================

/**
 * All available translation namespaces
 *
 * @example "home" | "about" | "common"
 */
declare type TranslationNamespace =
  | 'board'
  | 'board-detail'
  | 'board-write'
  | 'common'
  | 'login-redirect'
  | 'login-select'
  | 'maintenance'
  | 'make-quiz'
  | 'privacy-policy'
  | 'quiz-explanation'
  | 'quiz-history'
  | 'quiz-history-detail'
  | 'quiz-result'
  | 'solve-quiz'
  | 'terms-of-service';

declare type BoardKeys =
  | '건'
  | '게시글 목록을 불러올 수 없습니다.'
  | '답변완료'
  | '대기중'
  | '데이터를 불러오는데 실패했습니다.'
  | '로그인이 필요한 서비스입니다.\n로그인 페이지로 이동하시겠습니까?'
  | '문의 게시판'
  | '문의 작성하기'
  | '문의하기'
  | '변경사항'
  | '변경사항 목록을 불러올 수 없습니다.'
  | '상태'
  | '아직 등록된 문의가 없습니다'
  | '아직 등록된 변경사항이 없습니다'
  | '작성'
  | '작성일'
  | '작성자'
  | '제목'
  | '총';

declare type BoardDetailKeys =
  | '게시글이 삭제되었습니다.'
  | '관리자'
  | '글 내용을 입력해주세요.'
  | '답변완료'
  | '답변을 입력하세요...'
  | '대기중'
  | '댓글 {{expr0}}건'
  | '댓글이 등록되었습니다.'
  | '목록'
  | '문의 게시판'
  | '변경사항'
  | '삭제'
  | '상세'
  | '수정'
  | '아직 등록된 댓글이 없습니다.'
  | '정말로 이 게시글을 삭제하시겠습니까?';

/** Interpolation variables for "board-detail" namespace keys */
declare type BoardDetailKeyVariables = {
  '댓글 {{expr0}}건': 'expr0';
};

declare type BoardWriteKeys =
  | '내용'
  | '등록'
  | '등록 중...'
  | '등록하기'
  | '로그인이 필요합니다.'
  | '마크다운으로 변경사항을 작성해주세요.'
  | '문의 내용을 상세히 적어주세요.'
  | '문의 수정'
  | '변경사항 수정'
  | '변경사항 작성'
  | '새 문의 작성'
  | '수정'
  | '수정 권한이 없습니다.'
  | '수정 중...'
  | '수정완료'
  | '이미지 업로드'
  | '이미지 업로드 (jpg, png, gif, webp)'
  | '이미지 업로드 실패'
  | '이미지 업로드 중...'
  | '제목'
  | '제목과 내용을 모두 입력해주세요.'
  | '제목을 입력해주세요'
  | '취소';

declare type CommonKeys =
  | '2023년'
  | '2024년'
  | 'BLANK Mock 퀴즈'
  | 'ESSAY Mock 퀴즈'
  | 'Mermaid 렌더링 실패'
  | 'Mock 퀴즈'
  | 'Q-Asker 이메일 문의'
  | 'REAL_BLANK Mock 퀴즈'
  | '개'
  | '개념을 자신의 언어로 설명하는 서술형 문제'
  | '개인정보 처리방침'
  | '건의사항 / 피드백'
  | '걸린 시간'
  | '검토함'
  | '공지'
  | '광주'
  | '기록 삭제 실패:'
  | '기록을 찾을 수 없습니다.'
  | '기록이 삭제되었습니다.'
  | '닉네임 변경'
  | '닉네임 변경에 실패했습니다.'
  | '닉네임이 변경되었습니다.'
  | '다이어그램 로딩 중...'
  | '닫기'
  | '대구'
  | '로그아웃'
  | '로그아웃되었습니다.'
  | '로그인'
  | '로그인하고, 퀴즈기록을 저장해보세요'
  | '마지막 문제입니다.'
  | '모드'
  | '모든 기록을 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다.'
  | '모든 기록이 삭제되었습니다.'
  | '모범답'
  | '문의 및 피드백'
  | '문의하기'
  | '문제 수'
  | '미분류로 이동했습니다.'
  | '부산'
  | '불편한 점이나 개선 아이디어를 자유롭게 남겨주세요.'
  | '빈칸'
  | '사용자'
  | '생성 조건을 불러오지 못했어요. 옵션 화면에서 새로 만들어주세요.'
  | '서비스 이용약관'
  | '서울'
  | '소중한 의견 감사합니다!'
  | '순수 암기나 단순 이해를 묻는 문제'
  | '알 수 없는 오류가 발생했습니다.'
  | '알 수 없다'
  | '예) 광합성 과정에서 빛 반응과 암반응의 차이점을 설명하시오.'
  | '예) 다음 표를 보고 물음에 답하시오.\n\n| 연도 | 수출액 | 수입액 |\n|------|--------|--------|\n| 2023 | 120억 | 80억 |\n| 2024 | 90억 | 110억 |\n\n무역수지가 적자로 전환된 연도는?'
  | '예) 대한민국의 수도는 _______이다.'
  | '예) 지구는 태양 주위를 돈다.'
  | '오답'
  | '오답이 없습니다!'
  | '옳고 그름을 판별하는 문제'
  | '요청을 처리하지 못했습니다.'
  | '이 기록을 삭제하시겠습니까?'
  | '이 폴더를 삭제할까요? 안의 기록은 미분류로 이동합니다.'
  | '이어서 풀려면 남은 설정을 확인하고 문제를 생성해주세요.'
  | '인정된 답'
  | '입력 X'
  | '입력한 답:'
  | '전송'
  | '전송 중...'
  | '전송에 실패했습니다. 다시 시도해주세요.'
  | '전체 기록 삭제 실패:'
  | '점'
  | '정답'
  | '정답 답안:'
  | '제목 변경 실패:'
  | '제목 수정'
  | '제목은 100자 이하여야 합니다.'
  | '제목이 변경되었습니다.'
  | '지원하지 않는 파일 형식입니다'
  | '채점 중 오류가 발생했습니다.'
  | '추론, 문제 해결, 자료 해석을 요구하는 문제'
  | '퀴즈 기록'
  | '퀴즈 기록 불러오기 실패:'
  | '테마'
  | '테마 설정'
  | '파일 업로드 실패:'
  | '파일 크기는 {{expr0}}MB를 초과할 수 없습니다.'
  | '파일을 먼저 업로드해주세요.'
  | '페이지 범위를 올바르게 입력해주세요.'
  | '페이지를 선택해주세요.'
  | '폴더 목록 불러오기 실패:'
  | '폴더 이름은 50자 이하여야 합니다.'
  | '폴더 이름을 입력해주세요.'
  | '폴더 이름이 변경되었습니다.'
  | '폴더가 삭제되었습니다.'
  | '폴더가 생성되었습니다.'
  | '폴더는 최대 100개까지 만들 수 있습니다.'
  | '폴더로 이동했습니다.'
  | '폴더를 찾을 수 없습니다.'
  | '피드백 보내기'
  | '한국어'
  | '해당 없음'
  | '해설 정보를 불러오지 못했습니다.'
  | '해설이 없습니다.';

/** Interpolation variables for "common" namespace keys */
declare type CommonKeyVariables = {
  '파일 크기는 {{expr0}}MB를 초과할 수 없습니다.': 'expr0';
};

/** Translation keys for "login-redirect" namespace */
declare type LoginRedirectKeys = '로그인 리다이렉트 실패:' | '로그인 처리 중...';

declare type LoginSelectKeys =
  | 'AI 기반 자동 퀴즈 생성'
  | 'AI가 만드는 나만의 퀴즈'
  | '개인정보 처리방침'
  | '구글 로그인'
  | '다양한 파일 형식 지원'
  | '로그인'
  | '로그인 시'
  | '로그인이 필요합니다.'
  | '및'
  | '서비스 이용약관'
  | '소셜 계정으로 간편하게 시작하세요'
  | '에 동의하게 됩니다.'
  | '즉시 풀고 결과 확인'
  | '카카오 로그인';

/** Translation keys for "maintenance" namespace */
declare type MaintenanceKeys =
  | '더 나은 서비스를 위해 시스템을 점검하고 있습니다.'
  | '빠른 시일 내에 다시 찾아뵙겠습니다.'
  | '새로고침'
  | '서비스 점검 중입니다';

declare type MakeQuizKeys =
  | '(최대'
  | ', '
  | '1. 빈칸 채우기로 핵심 개념을 정리하세요.'
  | '2. OX로 빠르게 개념을 점검하세요.'
  | '24시간 후 자동 삭제되며 별도로 저장, 공유되지 않습니다.'
  | '3. 객관식으로 개념을 응용해 보세요.'
  | 'AI 퀴즈 만들기 6단계 가이드'
  | 'AI 퀴즈 활용 200% 팁'
  | 'AI는 실수를 할 수 있습니다. 학습 보조 도구로 활용해 주세요.'
  | 'AI에게 원하는 지시사항을 입력하세요. (선택 사항) \n 예) ~스타일로 만들어줘 \n 예) ~유형으로 만들어줘'
  | 'AI에게 원하는 지시사항을 작성하고'
  | 'OX 퀴즈'
  | 'PDF 로딩 중...'
  | 'PDF, PPT, Word 파일만 올리면 AI가 시험 문제를 자동으로 만들어줍니다. 객관식, OX, 빈칸 채우기 문제를 무료로 생성하세요.'
  | 'Q-Asker - AI가 시험 문제 만들어주는 무료 퀴즈 생성기'
  | 'Q-Asker는 PDF, PPT, Word 파일을 업로드하면 AI가 빈칸 채우기, OX, 객관식 퀴즈를 자동 생성하는 무료 웹 서비스입니다. 최대 50MB 파일을 업로드하고 페이지 범위와 문제 수(5~30개)를 선택하면 수십 초 내에 퀴즈가 생성됩니다. 스캔 문서도 OCR로 지원되며, 업로드된 파일은 24시간 후 자동 삭제됩니다. 상업적 목적이나 AI 학습에 사용되지 않습니다. 채점 결과와 함께 모든 문제의 상세 해설과 원본 페이지 참조를 제공하며, 생성된 퀴즈는 히스토리에 자동 저장됩니다.'
  | 'Q-Asker를 신뢰할 수 있는 이유'
  | '[한국어 특화] Q-Asker: AI가 한국어로 시험 문제 바로 만들어줘요!'
  | '가지고 계신 학습 자료로 AI 퀴즈를 만드는 가장 쉬운 방법을 알려드립니다.'
  | '개인정보 처리방침'
  | '객관식'
  | '기다리시는 동안.. 건의사항 / 피드백 있으면 부탁드립니다!'
  | '꼭 읽어주세요: 주의사항'
  | '끝 페이지'
  | '다른 문제 생성'
  | '다른 파일 넣기'
  | '다시 시도'
  | '더 많은 페이지 로딩 중... ('
  | '도움말 보기'
  | '또는'
  | '명확한 문제 생성 기준'
  | '모든 자료는 업로드 이후 24시간 뒤에 삭제됩니다'
  | '문제'
  | '문제 개수를 지정하세요'
  | '문제 생성 중...'
  | '문제 생성하기'
  | '문제 수'
  | '문제 유형별 기준에 맞춰 퀴즈를 생성합니다.'
  | '문제 풀기'
  | '문제를 생성하세요'
  | '미리보기 끄기'
  | '미리보기 켜기'
  | '방금 푼 세트와 같은 조건으로 새 문제를 이어서 생성합니다.'
  | '범위 지정:'
  | '불편한 점이나 개선 아이디어를 자유롭게 남겨주세요.'
  | '빈칸 넣기'
  | '빈칸 직접입력'
  | '빈칸, OX, 객관식 유형을 번갈아 풀어보며 개념 이해와 기억을 균형 있게 강화하세요.'
  | '생성된 문제는 학습 참고용이며, 사실관계가 100% 정확하지 않을 수 있습니다. 중요한 정보는 반드시 원본과 교차 확인하세요.'
  | '생성된 문제의 개수는 간혹 지정한 개수와 맞지 않을 수 있습니다.'
  | '생성할 언어를 선택하세요'
  | '서비스 이용약관'
  | '서술형'
  | '선택된 페이지 수:'
  | '선택지 없이 답을 직접 입력합니다. 표기/띄어쓰기 차이로 정답 인정이 까다로울 수 있습니다.'
  | '소중한 의견 감사합니다!'
  | '시작 페이지'
  | '아래 조건으로 문제를 더 만들까요?'
  | '언어'
  | '업로드된 파일'
  | '에 동의하는 것입니다.'
  | '영어'
  | '이 조건으로 더 풀기'
  | '이 조건으로 만들기'
  | '자료'
  | '자료 보호'
  | '자주 묻는 질문 (FAQ)'
  | '잠시만 기다려 주세요'
  | '적용'
  | '전송'
  | '전송 중...'
  | '전송에 실패했습니다. 다시 시도해주세요.'
  | '전체 선택'
  | '전체 해제'
  | '제목 변경 실패:'
  | '제목이 변경되었습니다.'
  | '지원하는 파일'
  | '초'
  | '최근 변경사항'
  | '최근 작성 프롬프트 불러오기'
  | '추가 지시'
  | '취소'
  | '퀴즈 생성시'
  | '퀴즈 유형'
  | '퀴즈 타입을 선택하세요'
  | '퀴즈를 생성하기 위해'
  | '크기 제한'
  | '파일 변환 중'
  | '파일 삭제'
  | '파일 선택하기'
  | '파일 업로드 중'
  | '파일은 상업적 목적, AI 학습 목적으로 사용되지 않습니다.'
  | '파일을 PDF로 변환하고 있어요'
  | '파일을 업로드하세요'
  | '파일을 여기에 드래그하세요'
  | '파일이 존재하지 않습니다. 다시 업로드해주세요.'
  | '페이지'
  | '페이지 정보를 불러오는 중입니다. 잠시만 기다려주세요.'
  | '페이지를 지정하세요'
  | '한국어'
  | '현재 생성된 퀴즈가 사라집니다. 계속하시겠습니까?'
  | '현재 생성중입니다 조금만 더 기다려주세요!'
  | '회원가입 없이 바로 시작할 수 있어요.';

declare type PrivacyPolicyKeys =
  | '1. 수집하는 개인정보 항목'
  | '10. 개인정보 문의'
  | '11. 권익 침해 구제'
  | '12. 처리방침 변경'
  | '2. 개인정보의 이용 목적'
  | '3. 보관·이용 기간'
  | '4. 회원 탈퇴 및 삭제 요청'
  | '5. 개인정보의 제3자 제공'
  | '6. 개인정보 처리의 위탁'
  | '7. 정보주체의 권리·의무 및 행사 방법'
  | '8. 개인정보의 안전성 확보 조치'
  | '9. 만 14세 미만 아동'
  | 'AI 추론 (Vertex AI/Gemini), 임시 파일 저장 (GCS)'
  | 'AI 퀴즈 생성 기능 제공'
  | 'AI 호출 로그'
  | 'AI 호출 로그, 서술형 채점 로그'
  | 'AI 호출 시 자동'
  | 'CDN·DDoS 보호'
  | 'Cloudflare, Inc.'
  | 'Google LLC'
  | 'IP 주소'
  | 'IP 주소, 접속 로그'
  | 'IP·접속 로그'
  | 'OAuth Provider ID'
  | 'Oracle Cloud (OCI)'
  | 'PDF, 이미지'
  | 'Provider ID, prompt, AI 응답, 모델·토큰·응답시간'
  | 'Q-Asker(이하 "서비스")는 「개인정보보호법」을 준수하며, 이용자의 개인정보를 안전하게 보호하기 위해 본 처리방침을 수립·공개합니다.'
  | '개인정보 분쟁조정위원회 (kopico.go.kr / 1833-6972)'
  | '개인정보 처리방침'
  | '개인정보 침해신고센터 (privacy.kisa.or.kr / 118)'
  | '개인정보 침해에 대한 분쟁 조정·상담은 다음 기관에 신청할 수 있습니다.'
  | '고객 문의 응대'
  | '구분'
  | '모든 요청 시'
  | '목차'
  | '법령에 따라 보관이 요구되는 경우 해당 기간 동안 분리 보관 후 파기합니다.'
  | '보관 기간'
  | '본 처리방침은 법령·정책 변경에 따라 개정될 수 있으며, 변경 시 시행일 7일 전(이용자에게 불리한 변경은 30일 전) 서비스 내 공지합니다. 단, 이용자에게 편익을 주는 변경 또는 긴급한 법령·보안 대응이 필요한 경우에는 즉시 시행될 수 있습니다.'
  | '부정 이용 방지·보안 (Rate Limiting, 어뷰징 감지)'
  | '서비스 이용 시'
  | '서비스 품질 개선·운영 (오류 추적, 성능 분석)'
  | '서비스는 HTTPS(TLS) 암호화 통신, JWT 기반 접근 제어, DB 민감 설정값 Jasypt 암호화, Bucket4j 기반 Rate Limiting, Cloudflare/OCI 방화벽을 통해 개인정보를 보호합니다. 처리 담당자는 최소화하며 접근 권한은 역할 기반으로 관리합니다.'
  | '서비스는 「개인정보보호법」 제26조에 따라 수탁자의 안전한 처리를 관리·감독합니다.'
  | '서비스는 만 14세 이상을 서비스 대상으로 합니다. 만 14세 미만의 가입은 제한되며, 법정대리인 동의 없이 수집된 사실이 확인되면 즉시 삭제합니다.'
  | '서비스는 원칙적으로 개인정보를 제3자에게 제공하지 않습니다. 다만 이용자가 사전 동의한 경우 또는 법령에 따른 적법한 요청이 있는 경우 예외로 합니다.'
  | '서비스는 위 목적 외 용도(특히 AI 모델 학습, 마케팅, 제3자 판매)로 개인정보를 이용하지 않습니다.'
  | '소셜 로그인 시'
  | '수집 시점'
  | '수탁자'
  | '시행일: 2026-05-29'
  | '업로드 PDF (OCI), AI 처리용 임시 파일 (GCS)'
  | '업로드 PDF, prompt'
  | '업로드 파일(PDF/PPT/DOCX), 커스텀 지시사항, 생성한 퀴즈, 풀이 기록, 답변, 게시글·댓글'
  | '연락처'
  | '원본 파일·이미지 저장'
  | '위탁 업무'
  | '위탁 항목'
  | '이용자 삭제 또는 회원 탈퇴 시까지'
  | '이용자 활동'
  | '이용자가 Google·Kakao 소셜 로그인을 통해 가입·로그인하는 경우, 서비스는 해당 제공자로부터 Provider ID를 전달받습니다. 각 제공자의 개인정보 정책은 해당 사이트를 참고하시기 바랍니다.'
  | '이용자는 개인정보 열람·정정·삭제·처리정지·동의 철회 권리를 행사할 수 있습니다. 닉네임 변경 및 일부 데이터 삭제는 서비스 내에서 직접 수행 가능하며, 그 외 권리 행사는 contact@q-asker.com 으로 요청해 주시기 바랍니다.'
  | '자동 수집'
  | '최대 1일'
  | '최대 90일 (운영·보안 목적)'
  | '탈퇴 시 회원 계정과 콘텐츠(퀴즈 세트, 풀이 기록, 게시글)가 삭제됩니다.'
  | '풀이 기록, 게시글'
  | '풀이 기록·게시글은 서비스 내에서 이용자가 직접 삭제할 수 있습니다.'
  | '항목'
  | '홈으로'
  | '회원 계정, 퀴즈 세트'
  | '회원 식별 및 서비스 제공 (OAuth 인증, 이용자별 퀴즈 기록 관리)'
  | '회원 정보'
  | '회원 탈퇴 시까지'
  | '회원 탈퇴는 contact@q-asker.com 으로 요청하며, 영업일 기준 7일 이내 처리됩니다.';

declare type QuizExplanationKeys =
  | 'AI 피드백'
  | 'PDF 로딩 중...'
  | '검토함'
  | '내 답변'
  | '내 답안'
  | '다음'
  | '모범답안'
  | '미답안'
  | '슬라이드의'
  | '오답만'
  | '원본 PDF 열기'
  | '이전'
  | '점'
  | '정답'
  | '참조 자료'
  | '파일 링크가 만료되었습니다.'
  | '파일이 존재하지 않습니다.'
  | '페이지'
  | '해설'
  | '현재는 pdf 파일만 지원합니다.'
  | '홈으로';

declare type QuizHistoryKeys =
  | '내 퀴즈 기록'
  | '다시 풀기'
  | '로그인이 필요한 서비스입니다'
  | '로그인하기'
  | '만들기'
  | '문제'
  | '미분류'
  | '미분류 기록이 없습니다.'
  | '미분류로 빼기'
  | '미완료'
  | '삭제'
  | '상태'
  | '새 폴더'
  | '생성일'
  | '아직 만든 퀴즈가 없습니다'
  | '아직 만든 폴더가 없습니다. 새 폴더를 만들어보세요.'
  | '액션'
  | '완료'
  | '완료율'
  | '완료일'
  | '완료한 퀴즈'
  | '이 폴더에 기록이 없습니다.'
  | '저장'
  | '전체'
  | '전체 삭제'
  | '점'
  | '점수'
  | '제목'
  | '지금까지 만들고 푼 퀴즈들을 확인해보세요'
  | '총 퀴즈 수'
  | '취소'
  | '퀴즈 기록은 로그인 후에 확인할 수 있습니다.'
  | '퀴즈 만들기'
  | '퀴즈 유형'
  | '퀴즈 풀기'
  | '퀴즈를 만들어서 문제를 풀어보세요!'
  | '평균 점수'
  | '폴더 삭제'
  | '폴더 이름'
  | '폴더 이름 변경'
  | '폴더 이름을 입력하세요.'
  | '폴더로 이동';

/** Translation keys for "quiz-history-detail" namespace */
declare type QuizHistoryDetailKeys =
  | '기록을 불러오는데 실패했습니다.'
  | '내 답변'
  | '모범답안'
  | '목록으로'
  | '부분 정답'
  | '점'
  | '정답'
  | '총점'
  | '해설 보기';

declare type QuizResultKeys =
  | '내 답변'
  | '모범답안'
  | '문제 미채점'
  | '미채점'
  | '부분 정답'
  | '점'
  | '정답'
  | '채점하지 않고 제출되었습니다'
  | '총점'
  | '해설 보기'
  | '홈으로';

declare type SolveQuizKeys =
  | 'AI 지시사항 반영 결과'
  | '{{n}}번째 빈칸'
  | '{{n}}번째 빈칸을 클릭하여 답 입력'
  | '{{n}}번째 빈칸의 답을 입력하세요'
  | '{{quizItem_userAnswer}}번'
  | '개'
  | '검토'
  | '검토할 문제:'
  | '다시 채점하기'
  | '다음'
  | '닫기'
  | '답변을 입력하세요'
  | '답변한 문제:'
  | '답을 직접 입력하세요'
  | '로그인 후 이어서 풀 수 있습니다.'
  | '로그인하고 기록하기'
  | '문제 목록'
  | '미선택'
  | '번:'
  | '베타 버전입니다! 건의사항 / 피드백 있으면 부탁드립니다!'
  | '불편한 점이나 개선 아이디어를 자유롭게 남겨주세요.'
  | '빈칸을 클릭하여 답 입력'
  | '선택지 보기'
  | '선택지 숨기기'
  | '소중한 의견 감사합니다!'
  | '시도'
  | '시도에 따라 단계별 힌트가 제시됩니다!'
  | '안푼 문제:'
  | '이전'
  | '입력한 답안'
  | '전송'
  | '전송 중...'
  | '전송에 실패했습니다. 다시 시도해주세요.'
  | '전체 문제:'
  | '점'
  | '제출 확인'
  | '제출하기'
  | '진행 상태가 저장되었습니다.'
  | '진행 현황'
  | '진행률'
  | '채점 실패'
  | '채점 중...'
  | '채점하기'
  | '추가 피드백 작성'
  | '취소'
  | '퀴즈 기록 중'
  | '확인';

/** Interpolation variables for "solve-quiz" namespace keys */
declare type SolveQuizKeyVariables = {
  '{{n}}번째 빈칸': 'n';
  '{{n}}번째 빈칸을 클릭하여 답 입력': 'n';
  '{{n}}번째 빈칸의 답을 입력하세요': 'n';
  '{{quizItem_userAnswer}}번': 'quizItem_userAnswer';
};

declare type TermsOfServiceKeys =
  | '1. 서비스 소개'
  | '2. 회원가입 및 계정'
  | '3. 회원 탈퇴'
  | '4. 이용자의 의무'
  | '5. 파일 및 콘텐츠'
  | '6. AI 생성 결과의 특성'
  | '7. 서비스 제공·변경·중단 및 면책'
  | '8. 약관 변경 및 분쟁 해결'
  | '9. 문의처'
  | 'AI 생성 결과의 상업적 재판매·무단 대량 배포'
  | 'Q-Asker(이하 "서비스")를 이용해 주셔서 감사합니다. 본 약관은 서비스 이용 조건을 규정합니다.'
  | 'Q-Asker는 소셜 로그인만 지원합니다.'
  | 'Q-Asker는 학습 자료를 업로드하면 AI가 자동으로 다양한 유형의 퀴즈를 생성하는 무료 웹 서비스입니다. 회원가입 없이 이용 가능하며, 로그인 시 풀이 기록 저장 등의 기능이 제공됩니다.'
  | '닉네임은 이용자가 변경할 수 있으며, 타인 사칭·욕설·혐오 표현은 서비스가 제한·변경할 수 있습니다.'
  | '동일 자료에서도 호출마다 결과가 다를 수 있습니다.'
  | '목차'
  | '무료로 제공되는 본 서비스의 이용으로 인한 직접·간접·부수적 손해에 대해 서비스의 고의 또는 중대한 과실이 없는 한 책임을 부담하지 않습니다.'
  | '본 서비스는 만 14세 이상을 대상으로 합니다.'
  | '본 약관은 대한민국 법률에 따라 해석되며, 분쟁은 대한민국 법원을 관할로 합니다.'
  | '본 약관은 변경 시 시행일 7일 전(이용자에게 불리한 변경은 30일 전) 서비스 내 공지합니다. 단, 이용자에게 편익을 주는 변경 또는 긴급한 법령·보안 대응이 필요한 경우에는 즉시 시행될 수 있습니다.'
  | '사실 오류·편향·누락이 있을 수 있으므로 학습 보조 도구로만 활용하고, 중요한 용도(시험·평가 등)에는 반드시 직접 검증해야 합니다.'
  | '서비스 이용약관'
  | '서비스는 사전 고지 없이 서비스 일부 또는 전부의 기능을 변경·중단할 수 있습니다.'
  | '서비스를 불법·비윤리적 목적으로 사용'
  | '시행일 이후 이용을 계속하면 변경에 동의한 것으로 간주합니다.'
  | '시행일: 2026-05-29'
  | '업로드한 파일은 퀴즈 생성 목적으로만 처리되며, AI 학습 데이터로 사용되지 않습니다.'
  | '외부 서비스(Google Gemini, OCI, GCS, Cloudflare 등)의 장애·정책 변경, 천재지변, 시스템 장애로 인한 손해에 대해 서비스는 책임지지 않습니다.'
  | '위반 시 서비스는 사전 통지 없이 이용을 제한·정지하거나 계정을 삭제할 수 있습니다.'
  | '음란·폭력·차별·혐오 콘텐츠 생성·게시'
  | '이메일: contact@q-asker.com'
  | '이용자는 다음 행위를 하지 않아야 합니다.'
  | '자동화된 수단(크롤러, 봇, 스크립트)으로 접근하거나 Rate Limit을 우회하는 행위'
  | '저작권 침해 신고는 문의처로 접수해 주시기 바랍니다.'
  | '퀴즈는 Google Gemini의 추론 결과이며, 서비스는 정확성·완전성을 보장하지 않습니다.'
  | '타 이용자의 계정·기록을 무단 조회·변경하려는 시도'
  | '타인의 저작권·초상권·상표권을 침해하는 파일 업로드'
  | '파일은 최대 1일 후 자동 삭제됩니다.'
  | '파일의 저작권은 이용자에게 있으며, 서비스는 위 목적 범위 내 일시적 이용권만 가집니다.'
  | '홈으로'
  | '회원 탈퇴는 contact@q-asker.com 으로 요청하며, 영업일 기준 7일 이내 처리됩니다.';

/**
 * Maps namespace names to their translation keys
 */
declare type TranslationKeys = {
  board: BoardKeys;
  'board-detail': BoardDetailKeys;
  'board-write': BoardWriteKeys;
  common: CommonKeys;
  'login-redirect': LoginRedirectKeys;
  'login-select': LoginSelectKeys;
  maintenance: MaintenanceKeys;
  'make-quiz': MakeQuizKeys;
  'privacy-policy': PrivacyPolicyKeys;
  'quiz-explanation': QuizExplanationKeys;
  'quiz-history': QuizHistoryKeys;
  'quiz-history-detail': QuizHistoryDetailKeys;
  'quiz-result': QuizResultKeys;
  'solve-quiz': SolveQuizKeys;
  'terms-of-service': TermsOfServiceKeys;
};

/**
 * Translation shape for createI18n().
 *
 * Generated locale entrypoints can use this type without importing JSON at runtime:
 * createI18n({} as I18nexusGeneratedTranslations, { fallbackNamespace: "common" })
 */
export type I18nexusGeneratedTranslations = {
  readonly board: {
    readonly en: {
      readonly 건: string;
      readonly '게시글 목록을 불러올 수 없습니다.': string;
      readonly 답변완료: string;
      readonly 대기중: string;
      readonly '데이터를 불러오는데 실패했습니다.': string;
      readonly '로그인이 필요한 서비스입니다.\n로그인 페이지로 이동하시겠습니까?': string;
      readonly '문의 게시판': string;
      readonly '문의 작성하기': string;
      readonly 문의하기: string;
      readonly 변경사항: string;
      readonly '변경사항 목록을 불러올 수 없습니다.': string;
      readonly 상태: string;
      readonly '아직 등록된 문의가 없습니다': string;
      readonly '아직 등록된 변경사항이 없습니다': string;
      readonly 작성: string;
      readonly 작성일: string;
      readonly 작성자: string;
      readonly 제목: string;
      readonly 총: string;
    };
    readonly ko: {
      readonly 건: string;
      readonly '게시글 목록을 불러올 수 없습니다.': string;
      readonly 답변완료: string;
      readonly 대기중: string;
      readonly '데이터를 불러오는데 실패했습니다.': string;
      readonly '로그인이 필요한 서비스입니다.\n로그인 페이지로 이동하시겠습니까?': string;
      readonly '문의 게시판': string;
      readonly '문의 작성하기': string;
      readonly 문의하기: string;
      readonly 변경사항: string;
      readonly '변경사항 목록을 불러올 수 없습니다.': string;
      readonly 상태: string;
      readonly '아직 등록된 문의가 없습니다': string;
      readonly '아직 등록된 변경사항이 없습니다': string;
      readonly 작성: string;
      readonly 작성일: string;
      readonly 작성자: string;
      readonly 제목: string;
      readonly 총: string;
    };
  };
  readonly 'board-detail': {
    readonly en: {
      readonly '게시글이 삭제되었습니다.': string;
      readonly 관리자: string;
      readonly '글 내용을 입력해주세요.': string;
      readonly 답변완료: string;
      readonly '답변을 입력하세요...': string;
      readonly 대기중: string;
      readonly '댓글 {{expr0}}건': string;
      readonly '댓글이 등록되었습니다.': string;
      readonly 목록: string;
      readonly '문의 게시판': string;
      readonly 변경사항: string;
      readonly 삭제: string;
      readonly 상세: string;
      readonly 수정: string;
      readonly '아직 등록된 댓글이 없습니다.': string;
      readonly '정말로 이 게시글을 삭제하시겠습니까?': string;
    };
    readonly ko: {
      readonly '게시글이 삭제되었습니다.': string;
      readonly 관리자: string;
      readonly '글 내용을 입력해주세요.': string;
      readonly 답변완료: string;
      readonly '답변을 입력하세요...': string;
      readonly 대기중: string;
      readonly '댓글 {{expr0}}건': string;
      readonly '댓글이 등록되었습니다.': string;
      readonly 목록: string;
      readonly '문의 게시판': string;
      readonly 변경사항: string;
      readonly 삭제: string;
      readonly 상세: string;
      readonly 수정: string;
      readonly '아직 등록된 댓글이 없습니다.': string;
      readonly '정말로 이 게시글을 삭제하시겠습니까?': string;
    };
  };
  readonly 'board-write': {
    readonly en: {
      readonly 내용: string;
      readonly 등록: string;
      readonly '등록 중...': string;
      readonly 등록하기: string;
      readonly '로그인이 필요합니다.': string;
      readonly '마크다운으로 변경사항을 작성해주세요.': string;
      readonly '문의 내용을 상세히 적어주세요.': string;
      readonly '문의 수정': string;
      readonly '변경사항 수정': string;
      readonly '변경사항 작성': string;
      readonly '새 문의 작성': string;
      readonly 수정: string;
      readonly '수정 권한이 없습니다.': string;
      readonly '수정 중...': string;
      readonly 수정완료: string;
      readonly '이미지 업로드': string;
      readonly '이미지 업로드 (jpg, png, gif, webp)': string;
      readonly '이미지 업로드 실패': string;
      readonly '이미지 업로드 중...': string;
      readonly 제목: string;
      readonly '제목과 내용을 모두 입력해주세요.': string;
      readonly '제목을 입력해주세요': string;
      readonly 취소: string;
    };
    readonly ko: {
      readonly 내용: string;
      readonly 등록: string;
      readonly '등록 중...': string;
      readonly 등록하기: string;
      readonly '로그인이 필요합니다.': string;
      readonly '마크다운으로 변경사항을 작성해주세요.': string;
      readonly '문의 내용을 상세히 적어주세요.': string;
      readonly '문의 수정': string;
      readonly '변경사항 수정': string;
      readonly '변경사항 작성': string;
      readonly '새 문의 작성': string;
      readonly 수정: string;
      readonly '수정 권한이 없습니다.': string;
      readonly '수정 중...': string;
      readonly 수정완료: string;
      readonly '이미지 업로드': string;
      readonly '이미지 업로드 (jpg, png, gif, webp)': string;
      readonly '이미지 업로드 실패': string;
      readonly '이미지 업로드 중...': string;
      readonly 제목: string;
      readonly '제목과 내용을 모두 입력해주세요.': string;
      readonly '제목을 입력해주세요': string;
      readonly 취소: string;
    };
  };
  readonly common: {
    readonly en: {
      readonly '2023년': string;
      readonly '2024년': string;
      readonly 'BLANK Mock 퀴즈': string;
      readonly 'ESSAY Mock 퀴즈': string;
      readonly 'Mermaid 렌더링 실패': string;
      readonly 'Mock 퀴즈': string;
      readonly 'Q-Asker 이메일 문의': string;
      readonly 'REAL_BLANK Mock 퀴즈': string;
      readonly 개: string;
      readonly '개념을 자신의 언어로 설명하는 서술형 문제': string;
      readonly '개인정보 처리방침': string;
      readonly '건의사항 / 피드백': string;
      readonly '걸린 시간': string;
      readonly 검토함: string;
      readonly 공지: string;
      readonly 광주: string;
      readonly '기록 삭제 실패:': string;
      readonly '기록을 찾을 수 없습니다.': string;
      readonly '기록이 삭제되었습니다.': string;
      readonly '닉네임 변경': string;
      readonly '닉네임 변경에 실패했습니다.': string;
      readonly '닉네임이 변경되었습니다.': string;
      readonly '다이어그램 로딩 중...': string;
      readonly 닫기: string;
      readonly 대구: string;
      readonly 로그아웃: string;
      readonly '로그아웃되었습니다.': string;
      readonly 로그인: string;
      readonly '로그인하고, 퀴즈기록을 저장해보세요': string;
      readonly '마지막 문제입니다.': string;
      readonly 모드: string;
      readonly '모든 기록을 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다.': string;
      readonly '모든 기록이 삭제되었습니다.': string;
      readonly 모범답: string;
      readonly '문의 및 피드백': string;
      readonly 문의하기: string;
      readonly '문제 수': string;
      readonly '미분류로 이동했습니다.': string;
      readonly 부산: string;
      readonly '불편한 점이나 개선 아이디어를 자유롭게 남겨주세요.': string;
      readonly 빈칸: string;
      readonly 사용자: string;
      readonly '생성 조건을 불러오지 못했어요. 옵션 화면에서 새로 만들어주세요.': string;
      readonly '서비스 이용약관': string;
      readonly 서울: string;
      readonly '소중한 의견 감사합니다!': string;
      readonly '순수 암기나 단순 이해를 묻는 문제': string;
      readonly '알 수 없는 오류가 발생했습니다.': string;
      readonly '알 수 없다': string;
      readonly '예) 광합성 과정에서 빛 반응과 암반응의 차이점을 설명하시오.': string;
      readonly '예) 다음 표를 보고 물음에 답하시오.\n\n| 연도 | 수출액 | 수입액 |\n|------|--------|--------|\n| 2023 | 120억 | 80억 |\n| 2024 | 90억 | 110억 |\n\n무역수지가 적자로 전환된 연도는?': string;
      readonly '예) 대한민국의 수도는 _______이다.': string;
      readonly '예) 지구는 태양 주위를 돈다.': string;
      readonly 오답: string;
      readonly '오답이 없습니다!': string;
      readonly '옳고 그름을 판별하는 문제': string;
      readonly '요청을 처리하지 못했습니다.': string;
      readonly '이 기록을 삭제하시겠습니까?': string;
      readonly '이 폴더를 삭제할까요? 안의 기록은 미분류로 이동합니다.': string;
      readonly '이어서 풀려면 남은 설정을 확인하고 문제를 생성해주세요.': string;
      readonly '인정된 답': string;
      readonly '입력 X': string;
      readonly '입력한 답:': string;
      readonly 전송: string;
      readonly '전송 중...': string;
      readonly '전송에 실패했습니다. 다시 시도해주세요.': string;
      readonly '전체 기록 삭제 실패:': string;
      readonly 점: string;
      readonly 정답: string;
      readonly '정답 답안:': string;
      readonly '제목 변경 실패:': string;
      readonly '제목 수정': string;
      readonly '제목은 100자 이하여야 합니다.': string;
      readonly '제목이 변경되었습니다.': string;
      readonly '지원하지 않는 파일 형식입니다': string;
      readonly '채점 중 오류가 발생했습니다.': string;
      readonly '추론, 문제 해결, 자료 해석을 요구하는 문제': string;
      readonly '퀴즈 기록': string;
      readonly '퀴즈 기록 불러오기 실패:': string;
      readonly 테마: string;
      readonly '테마 설정': string;
      readonly '파일 업로드 실패:': string;
      readonly '파일 크기는 {{expr0}}MB를 초과할 수 없습니다.': string;
      readonly '파일을 먼저 업로드해주세요.': string;
      readonly '페이지 범위를 올바르게 입력해주세요.': string;
      readonly '페이지를 선택해주세요.': string;
      readonly '폴더 목록 불러오기 실패:': string;
      readonly '폴더 이름은 50자 이하여야 합니다.': string;
      readonly '폴더 이름을 입력해주세요.': string;
      readonly '폴더 이름이 변경되었습니다.': string;
      readonly '폴더가 삭제되었습니다.': string;
      readonly '폴더가 생성되었습니다.': string;
      readonly '폴더는 최대 100개까지 만들 수 있습니다.': string;
      readonly '폴더로 이동했습니다.': string;
      readonly '폴더를 찾을 수 없습니다.': string;
      readonly '피드백 보내기': string;
      readonly 한국어: string;
      readonly '해당 없음': string;
      readonly '해설 정보를 불러오지 못했습니다.': string;
      readonly '해설이 없습니다.': string;
    };
    readonly ko: {
      readonly '2023년': string;
      readonly '2024년': string;
      readonly 'BLANK Mock 퀴즈': string;
      readonly 'ESSAY Mock 퀴즈': string;
      readonly 'Mermaid 렌더링 실패': string;
      readonly 'Mock 퀴즈': string;
      readonly 'Q-Asker 이메일 문의': string;
      readonly 'REAL_BLANK Mock 퀴즈': string;
      readonly 개: string;
      readonly '개념을 자신의 언어로 설명하는 서술형 문제': string;
      readonly '개인정보 처리방침': string;
      readonly '건의사항 / 피드백': string;
      readonly '걸린 시간': string;
      readonly 검토함: string;
      readonly 공지: string;
      readonly 광주: string;
      readonly '기록 삭제 실패:': string;
      readonly '기록을 찾을 수 없습니다.': string;
      readonly '기록이 삭제되었습니다.': string;
      readonly '닉네임 변경': string;
      readonly '닉네임 변경에 실패했습니다.': string;
      readonly '닉네임이 변경되었습니다.': string;
      readonly '다이어그램 로딩 중...': string;
      readonly 닫기: string;
      readonly 대구: string;
      readonly 로그아웃: string;
      readonly '로그아웃되었습니다.': string;
      readonly 로그인: string;
      readonly '로그인하고, 퀴즈기록을 저장해보세요': string;
      readonly '마지막 문제입니다.': string;
      readonly 모드: string;
      readonly '모든 기록을 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다.': string;
      readonly '모든 기록이 삭제되었습니다.': string;
      readonly 모범답: string;
      readonly '문의 및 피드백': string;
      readonly 문의하기: string;
      readonly '문제 수': string;
      readonly '미분류로 이동했습니다.': string;
      readonly 부산: string;
      readonly '불편한 점이나 개선 아이디어를 자유롭게 남겨주세요.': string;
      readonly 빈칸: string;
      readonly 사용자: string;
      readonly '생성 조건을 불러오지 못했어요. 옵션 화면에서 새로 만들어주세요.': string;
      readonly '서비스 이용약관': string;
      readonly 서울: string;
      readonly '소중한 의견 감사합니다!': string;
      readonly '순수 암기나 단순 이해를 묻는 문제': string;
      readonly '알 수 없는 오류가 발생했습니다.': string;
      readonly '알 수 없다': string;
      readonly '예) 광합성 과정에서 빛 반응과 암반응의 차이점을 설명하시오.': string;
      readonly '예) 다음 표를 보고 물음에 답하시오.\n\n| 연도 | 수출액 | 수입액 |\n|------|--------|--------|\n| 2023 | 120억 | 80억 |\n| 2024 | 90억 | 110억 |\n\n무역수지가 적자로 전환된 연도는?': string;
      readonly '예) 대한민국의 수도는 _______이다.': string;
      readonly '예) 지구는 태양 주위를 돈다.': string;
      readonly 오답: string;
      readonly '오답이 없습니다!': string;
      readonly '옳고 그름을 판별하는 문제': string;
      readonly '요청을 처리하지 못했습니다.': string;
      readonly '이 기록을 삭제하시겠습니까?': string;
      readonly '이 폴더를 삭제할까요? 안의 기록은 미분류로 이동합니다.': string;
      readonly '이어서 풀려면 남은 설정을 확인하고 문제를 생성해주세요.': string;
      readonly '인정된 답': string;
      readonly '입력 X': string;
      readonly '입력한 답:': string;
      readonly 전송: string;
      readonly '전송 중...': string;
      readonly '전송에 실패했습니다. 다시 시도해주세요.': string;
      readonly '전체 기록 삭제 실패:': string;
      readonly 점: string;
      readonly 정답: string;
      readonly '정답 답안:': string;
      readonly '제목 변경 실패:': string;
      readonly '제목 수정': string;
      readonly '제목은 100자 이하여야 합니다.': string;
      readonly '제목이 변경되었습니다.': string;
      readonly '지원하지 않는 파일 형식입니다': string;
      readonly '채점 중 오류가 발생했습니다.': string;
      readonly '추론, 문제 해결, 자료 해석을 요구하는 문제': string;
      readonly '퀴즈 기록': string;
      readonly '퀴즈 기록 불러오기 실패:': string;
      readonly 테마: string;
      readonly '테마 설정': string;
      readonly '파일 업로드 실패:': string;
      readonly '파일 크기는 {{expr0}}MB를 초과할 수 없습니다.': string;
      readonly '파일을 먼저 업로드해주세요.': string;
      readonly '페이지 범위를 올바르게 입력해주세요.': string;
      readonly '페이지를 선택해주세요.': string;
      readonly '폴더 목록 불러오기 실패:': string;
      readonly '폴더 이름은 50자 이하여야 합니다.': string;
      readonly '폴더 이름을 입력해주세요.': string;
      readonly '폴더 이름이 변경되었습니다.': string;
      readonly '폴더가 삭제되었습니다.': string;
      readonly '폴더가 생성되었습니다.': string;
      readonly '폴더는 최대 100개까지 만들 수 있습니다.': string;
      readonly '폴더로 이동했습니다.': string;
      readonly '폴더를 찾을 수 없습니다.': string;
      readonly '피드백 보내기': string;
      readonly 한국어: string;
      readonly '해당 없음': string;
      readonly '해설 정보를 불러오지 못했습니다.': string;
      readonly '해설이 없습니다.': string;
    };
  };
  readonly 'login-redirect': {
    readonly en: {
      readonly '로그인 리다이렉트 실패:': string;
      readonly '로그인 처리 중...': string;
    };
    readonly ko: {
      readonly '로그인 리다이렉트 실패:': string;
      readonly '로그인 처리 중...': string;
    };
  };
  readonly 'login-select': {
    readonly en: {
      readonly 'AI 기반 자동 퀴즈 생성': string;
      readonly 'AI가 만드는 나만의 퀴즈': string;
      readonly '개인정보 처리방침': string;
      readonly '구글 로그인': string;
      readonly '다양한 파일 형식 지원': string;
      readonly 로그인: string;
      readonly '로그인 시': string;
      readonly '로그인이 필요합니다.': string;
      readonly 및: string;
      readonly '서비스 이용약관': string;
      readonly '소셜 계정으로 간편하게 시작하세요': string;
      readonly '에 동의하게 됩니다.': string;
      readonly '즉시 풀고 결과 확인': string;
      readonly '카카오 로그인': string;
    };
    readonly ko: {
      readonly 'AI 기반 자동 퀴즈 생성': string;
      readonly 'AI가 만드는 나만의 퀴즈': string;
      readonly '개인정보 처리방침': string;
      readonly '구글 로그인': string;
      readonly '다양한 파일 형식 지원': string;
      readonly 로그인: string;
      readonly '로그인 시': string;
      readonly '로그인이 필요합니다.': string;
      readonly 및: string;
      readonly '서비스 이용약관': string;
      readonly '소셜 계정으로 간편하게 시작하세요': string;
      readonly '에 동의하게 됩니다.': string;
      readonly '즉시 풀고 결과 확인': string;
      readonly '카카오 로그인': string;
    };
  };
  readonly maintenance: {
    readonly en: {
      readonly '더 나은 서비스를 위해 시스템을 점검하고 있습니다.': string;
      readonly '빠른 시일 내에 다시 찾아뵙겠습니다.': string;
      readonly 새로고침: string;
      readonly '서비스 점검 중입니다': string;
    };
    readonly ko: {
      readonly '더 나은 서비스를 위해 시스템을 점검하고 있습니다.': string;
      readonly '빠른 시일 내에 다시 찾아뵙겠습니다.': string;
      readonly 새로고침: string;
      readonly '서비스 점검 중입니다': string;
    };
  };
  readonly 'make-quiz': {
    readonly en: {
      readonly '(최대': string;
      readonly ', ': string;
      readonly '1. 빈칸 채우기로 핵심 개념을 정리하세요.': string;
      readonly '2. OX로 빠르게 개념을 점검하세요.': string;
      readonly '24시간 후 자동 삭제되며 별도로 저장, 공유되지 않습니다.': string;
      readonly '3. 객관식으로 개념을 응용해 보세요.': string;
      readonly 'AI 퀴즈 만들기 6단계 가이드': string;
      readonly 'AI 퀴즈 활용 200% 팁': string;
      readonly 'AI는 실수를 할 수 있습니다. 학습 보조 도구로 활용해 주세요.': string;
      readonly 'AI에게 원하는 지시사항을 입력하세요. (선택 사항) \n 예) ~스타일로 만들어줘 \n 예) ~유형으로 만들어줘': string;
      readonly 'AI에게 원하는 지시사항을 작성하고': string;
      readonly 'OX 퀴즈': string;
      readonly 'PDF 로딩 중...': string;
      readonly 'PDF, PPT, Word 파일만 올리면 AI가 시험 문제를 자동으로 만들어줍니다. 객관식, OX, 빈칸 채우기 문제를 무료로 생성하세요.': string;
      readonly 'Q-Asker - AI가 시험 문제 만들어주는 무료 퀴즈 생성기': string;
      readonly 'Q-Asker는 PDF, PPT, Word 파일을 업로드하면 AI가 빈칸 채우기, OX, 객관식 퀴즈를 자동 생성하는 무료 웹 서비스입니다. 최대 50MB 파일을 업로드하고 페이지 범위와 문제 수(5~30개)를 선택하면 수십 초 내에 퀴즈가 생성됩니다. 스캔 문서도 OCR로 지원되며, 업로드된 파일은 24시간 후 자동 삭제됩니다. 상업적 목적이나 AI 학습에 사용되지 않습니다. 채점 결과와 함께 모든 문제의 상세 해설과 원본 페이지 참조를 제공하며, 생성된 퀴즈는 히스토리에 자동 저장됩니다.': string;
      readonly 'Q-Asker를 신뢰할 수 있는 이유': string;
      readonly '[한국어 특화] Q-Asker: AI가 한국어로 시험 문제 바로 만들어줘요!': string;
      readonly '가지고 계신 학습 자료로 AI 퀴즈를 만드는 가장 쉬운 방법을 알려드립니다.': string;
      readonly '개인정보 처리방침': string;
      readonly 객관식: string;
      readonly '기다리시는 동안.. 건의사항 / 피드백 있으면 부탁드립니다!': string;
      readonly '꼭 읽어주세요: 주의사항': string;
      readonly '끝 페이지': string;
      readonly '다른 문제 생성': string;
      readonly '다른 파일 넣기': string;
      readonly '다시 시도': string;
      readonly '더 많은 페이지 로딩 중... (': string;
      readonly '도움말 보기': string;
      readonly 또는: string;
      readonly '명확한 문제 생성 기준': string;
      readonly '모든 자료는 업로드 이후 24시간 뒤에 삭제됩니다': string;
      readonly 문제: string;
      readonly '문제 개수를 지정하세요': string;
      readonly '문제 생성 중...': string;
      readonly '문제 생성하기': string;
      readonly '문제 수': string;
      readonly '문제 유형별 기준에 맞춰 퀴즈를 생성합니다.': string;
      readonly '문제 풀기': string;
      readonly '문제를 생성하세요': string;
      readonly '미리보기 끄기': string;
      readonly '미리보기 켜기': string;
      readonly '방금 푼 세트와 같은 조건으로 새 문제를 이어서 생성합니다.': string;
      readonly '범위 지정:': string;
      readonly '불편한 점이나 개선 아이디어를 자유롭게 남겨주세요.': string;
      readonly '빈칸 넣기': string;
      readonly '빈칸 직접입력': string;
      readonly '빈칸, OX, 객관식 유형을 번갈아 풀어보며 개념 이해와 기억을 균형 있게 강화하세요.': string;
      readonly '생성된 문제는 학습 참고용이며, 사실관계가 100% 정확하지 않을 수 있습니다. 중요한 정보는 반드시 원본과 교차 확인하세요.': string;
      readonly '생성된 문제의 개수는 간혹 지정한 개수와 맞지 않을 수 있습니다.': string;
      readonly '생성할 언어를 선택하세요': string;
      readonly '서비스 이용약관': string;
      readonly 서술형: string;
      readonly '선택된 페이지 수:': string;
      readonly '선택지 없이 답을 직접 입력합니다. 표기/띄어쓰기 차이로 정답 인정이 까다로울 수 있습니다.': string;
      readonly '소중한 의견 감사합니다!': string;
      readonly '시작 페이지': string;
      readonly '아래 조건으로 문제를 더 만들까요?': string;
      readonly 언어: string;
      readonly '업로드된 파일': string;
      readonly '에 동의하는 것입니다.': string;
      readonly 영어: string;
      readonly '이 조건으로 더 풀기': string;
      readonly '이 조건으로 만들기': string;
      readonly 자료: string;
      readonly '자료 보호': string;
      readonly '자주 묻는 질문 (FAQ)': string;
      readonly '잠시만 기다려 주세요': string;
      readonly 적용: string;
      readonly 전송: string;
      readonly '전송 중...': string;
      readonly '전송에 실패했습니다. 다시 시도해주세요.': string;
      readonly '전체 선택': string;
      readonly '전체 해제': string;
      readonly '제목 변경 실패:': string;
      readonly '제목이 변경되었습니다.': string;
      readonly '지원하는 파일': string;
      readonly 초: string;
      readonly '최근 변경사항': string;
      readonly '최근 작성 프롬프트 불러오기': string;
      readonly '추가 지시': string;
      readonly 취소: string;
      readonly '퀴즈 생성시': string;
      readonly '퀴즈 유형': string;
      readonly '퀴즈 타입을 선택하세요': string;
      readonly '퀴즈를 생성하기 위해': string;
      readonly '크기 제한': string;
      readonly '파일 변환 중': string;
      readonly '파일 삭제': string;
      readonly '파일 선택하기': string;
      readonly '파일 업로드 중': string;
      readonly '파일은 상업적 목적, AI 학습 목적으로 사용되지 않습니다.': string;
      readonly '파일을 PDF로 변환하고 있어요': string;
      readonly '파일을 업로드하세요': string;
      readonly '파일을 여기에 드래그하세요': string;
      readonly '파일이 존재하지 않습니다. 다시 업로드해주세요.': string;
      readonly 페이지: string;
      readonly '페이지 정보를 불러오는 중입니다. 잠시만 기다려주세요.': string;
      readonly '페이지를 지정하세요': string;
      readonly 한국어: string;
      readonly '현재 생성된 퀴즈가 사라집니다. 계속하시겠습니까?': string;
      readonly '현재 생성중입니다 조금만 더 기다려주세요!': string;
      readonly '회원가입 없이 바로 시작할 수 있어요.': string;
    };
    readonly ko: {
      readonly '(최대': string;
      readonly ', ': string;
      readonly '1. 빈칸 채우기로 핵심 개념을 정리하세요.': string;
      readonly '2. OX로 빠르게 개념을 점검하세요.': string;
      readonly '24시간 후 자동 삭제되며 별도로 저장, 공유되지 않습니다.': string;
      readonly '3. 객관식으로 개념을 응용해 보세요.': string;
      readonly 'AI 퀴즈 만들기 6단계 가이드': string;
      readonly 'AI 퀴즈 활용 200% 팁': string;
      readonly 'AI는 실수를 할 수 있습니다. 학습 보조 도구로 활용해 주세요.': string;
      readonly 'AI에게 원하는 지시사항을 입력하세요. (선택 사항) \n 예) ~스타일로 만들어줘 \n 예) ~유형으로 만들어줘': string;
      readonly 'AI에게 원하는 지시사항을 작성하고': string;
      readonly 'OX 퀴즈': string;
      readonly 'PDF 로딩 중...': string;
      readonly 'PDF, PPT, Word 파일만 올리면 AI가 시험 문제를 자동으로 만들어줍니다. 객관식, OX, 빈칸 채우기 문제를 무료로 생성하세요.': string;
      readonly 'Q-Asker - AI가 시험 문제 만들어주는 무료 퀴즈 생성기': string;
      readonly 'Q-Asker는 PDF, PPT, Word 파일을 업로드하면 AI가 빈칸 채우기, OX, 객관식 퀴즈를 자동 생성하는 무료 웹 서비스입니다. 최대 50MB 파일을 업로드하고 페이지 범위와 문제 수(5~30개)를 선택하면 수십 초 내에 퀴즈가 생성됩니다. 스캔 문서도 OCR로 지원되며, 업로드된 파일은 24시간 후 자동 삭제됩니다. 상업적 목적이나 AI 학습에 사용되지 않습니다. 채점 결과와 함께 모든 문제의 상세 해설과 원본 페이지 참조를 제공하며, 생성된 퀴즈는 히스토리에 자동 저장됩니다.': string;
      readonly 'Q-Asker를 신뢰할 수 있는 이유': string;
      readonly '[한국어 특화] Q-Asker: AI가 한국어로 시험 문제 바로 만들어줘요!': string;
      readonly '가지고 계신 학습 자료로 AI 퀴즈를 만드는 가장 쉬운 방법을 알려드립니다.': string;
      readonly '개인정보 처리방침': string;
      readonly 객관식: string;
      readonly '기다리시는 동안.. 건의사항 / 피드백 있으면 부탁드립니다!': string;
      readonly '꼭 읽어주세요: 주의사항': string;
      readonly '끝 페이지': string;
      readonly '다른 문제 생성': string;
      readonly '다른 파일 넣기': string;
      readonly '다시 시도': string;
      readonly '더 많은 페이지 로딩 중... (': string;
      readonly '도움말 보기': string;
      readonly 또는: string;
      readonly '명확한 문제 생성 기준': string;
      readonly '모든 자료는 업로드 이후 24시간 뒤에 삭제됩니다': string;
      readonly 문제: string;
      readonly '문제 개수를 지정하세요': string;
      readonly '문제 생성 중...': string;
      readonly '문제 생성하기': string;
      readonly '문제 수': string;
      readonly '문제 유형별 기준에 맞춰 퀴즈를 생성합니다.': string;
      readonly '문제 풀기': string;
      readonly '문제를 생성하세요': string;
      readonly '미리보기 끄기': string;
      readonly '미리보기 켜기': string;
      readonly '방금 푼 세트와 같은 조건으로 새 문제를 이어서 생성합니다.': string;
      readonly '범위 지정:': string;
      readonly '불편한 점이나 개선 아이디어를 자유롭게 남겨주세요.': string;
      readonly '빈칸 넣기': string;
      readonly '빈칸 직접입력': string;
      readonly '빈칸, OX, 객관식 유형을 번갈아 풀어보며 개념 이해와 기억을 균형 있게 강화하세요.': string;
      readonly '생성된 문제는 학습 참고용이며, 사실관계가 100% 정확하지 않을 수 있습니다. 중요한 정보는 반드시 원본과 교차 확인하세요.': string;
      readonly '생성된 문제의 개수는 간혹 지정한 개수와 맞지 않을 수 있습니다.': string;
      readonly '생성할 언어를 선택하세요': string;
      readonly '서비스 이용약관': string;
      readonly 서술형: string;
      readonly '선택된 페이지 수:': string;
      readonly '선택지 없이 답을 직접 입력합니다. 표기/띄어쓰기 차이로 정답 인정이 까다로울 수 있습니다.': string;
      readonly '소중한 의견 감사합니다!': string;
      readonly '시작 페이지': string;
      readonly '아래 조건으로 문제를 더 만들까요?': string;
      readonly 언어: string;
      readonly '업로드된 파일': string;
      readonly '에 동의하는 것입니다.': string;
      readonly 영어: string;
      readonly '이 조건으로 더 풀기': string;
      readonly '이 조건으로 만들기': string;
      readonly 자료: string;
      readonly '자료 보호': string;
      readonly '자주 묻는 질문 (FAQ)': string;
      readonly '잠시만 기다려 주세요': string;
      readonly 적용: string;
      readonly 전송: string;
      readonly '전송 중...': string;
      readonly '전송에 실패했습니다. 다시 시도해주세요.': string;
      readonly '전체 선택': string;
      readonly '전체 해제': string;
      readonly '제목 변경 실패:': string;
      readonly '제목이 변경되었습니다.': string;
      readonly '지원하는 파일': string;
      readonly 초: string;
      readonly '최근 변경사항': string;
      readonly '최근 작성 프롬프트 불러오기': string;
      readonly '추가 지시': string;
      readonly 취소: string;
      readonly '퀴즈 생성시': string;
      readonly '퀴즈 유형': string;
      readonly '퀴즈 타입을 선택하세요': string;
      readonly '퀴즈를 생성하기 위해': string;
      readonly '크기 제한': string;
      readonly '파일 변환 중': string;
      readonly '파일 삭제': string;
      readonly '파일 선택하기': string;
      readonly '파일 업로드 중': string;
      readonly '파일은 상업적 목적, AI 학습 목적으로 사용되지 않습니다.': string;
      readonly '파일을 PDF로 변환하고 있어요': string;
      readonly '파일을 업로드하세요': string;
      readonly '파일을 여기에 드래그하세요': string;
      readonly '파일이 존재하지 않습니다. 다시 업로드해주세요.': string;
      readonly 페이지: string;
      readonly '페이지 정보를 불러오는 중입니다. 잠시만 기다려주세요.': string;
      readonly '페이지를 지정하세요': string;
      readonly 한국어: string;
      readonly '현재 생성된 퀴즈가 사라집니다. 계속하시겠습니까?': string;
      readonly '현재 생성중입니다 조금만 더 기다려주세요!': string;
      readonly '회원가입 없이 바로 시작할 수 있어요.': string;
    };
  };
  readonly 'privacy-policy': {
    readonly en: {
      readonly '1. 수집하는 개인정보 항목': string;
      readonly '10. 개인정보 문의': string;
      readonly '11. 권익 침해 구제': string;
      readonly '12. 처리방침 변경': string;
      readonly '2. 개인정보의 이용 목적': string;
      readonly '3. 보관·이용 기간': string;
      readonly '4. 회원 탈퇴 및 삭제 요청': string;
      readonly '5. 개인정보의 제3자 제공': string;
      readonly '6. 개인정보 처리의 위탁': string;
      readonly '7. 정보주체의 권리·의무 및 행사 방법': string;
      readonly '8. 개인정보의 안전성 확보 조치': string;
      readonly '9. 만 14세 미만 아동': string;
      readonly 'AI 추론 (Vertex AI/Gemini), 임시 파일 저장 (GCS)': string;
      readonly 'AI 퀴즈 생성 기능 제공': string;
      readonly 'AI 호출 로그': string;
      readonly 'AI 호출 로그, 서술형 채점 로그': string;
      readonly 'AI 호출 시 자동': string;
      readonly 'CDN·DDoS 보호': string;
      readonly 'Cloudflare, Inc.': string;
      readonly 'Google LLC': string;
      readonly 'IP 주소': string;
      readonly 'IP 주소, 접속 로그': string;
      readonly 'IP·접속 로그': string;
      readonly 'OAuth Provider ID': string;
      readonly 'Oracle Cloud (OCI)': string;
      readonly 'PDF, 이미지': string;
      readonly 'Provider ID, prompt, AI 응답, 모델·토큰·응답시간': string;
      readonly 'Q-Asker(이하 "서비스")는 「개인정보보호법」을 준수하며, 이용자의 개인정보를 안전하게 보호하기 위해 본 처리방침을 수립·공개합니다.': string;
      readonly '개인정보 분쟁조정위원회 (kopico.go.kr / 1833-6972)': string;
      readonly '개인정보 처리방침': string;
      readonly '개인정보 침해신고센터 (privacy.kisa.or.kr / 118)': string;
      readonly '개인정보 침해에 대한 분쟁 조정·상담은 다음 기관에 신청할 수 있습니다.': string;
      readonly '고객 문의 응대': string;
      readonly 구분: string;
      readonly '모든 요청 시': string;
      readonly 목차: string;
      readonly '법령에 따라 보관이 요구되는 경우 해당 기간 동안 분리 보관 후 파기합니다.': string;
      readonly '보관 기간': string;
      readonly '본 처리방침은 법령·정책 변경에 따라 개정될 수 있으며, 변경 시 시행일 7일 전(이용자에게 불리한 변경은 30일 전) 서비스 내 공지합니다. 단, 이용자에게 편익을 주는 변경 또는 긴급한 법령·보안 대응이 필요한 경우에는 즉시 시행될 수 있습니다.': string;
      readonly '부정 이용 방지·보안 (Rate Limiting, 어뷰징 감지)': string;
      readonly '서비스 이용 시': string;
      readonly '서비스 품질 개선·운영 (오류 추적, 성능 분석)': string;
      readonly '서비스는 HTTPS(TLS) 암호화 통신, JWT 기반 접근 제어, DB 민감 설정값 Jasypt 암호화, Bucket4j 기반 Rate Limiting, Cloudflare/OCI 방화벽을 통해 개인정보를 보호합니다. 처리 담당자는 최소화하며 접근 권한은 역할 기반으로 관리합니다.': string;
      readonly '서비스는 「개인정보보호법」 제26조에 따라 수탁자의 안전한 처리를 관리·감독합니다.': string;
      readonly '서비스는 만 14세 이상을 서비스 대상으로 합니다. 만 14세 미만의 가입은 제한되며, 법정대리인 동의 없이 수집된 사실이 확인되면 즉시 삭제합니다.': string;
      readonly '서비스는 원칙적으로 개인정보를 제3자에게 제공하지 않습니다. 다만 이용자가 사전 동의한 경우 또는 법령에 따른 적법한 요청이 있는 경우 예외로 합니다.': string;
      readonly '서비스는 위 목적 외 용도(특히 AI 모델 학습, 마케팅, 제3자 판매)로 개인정보를 이용하지 않습니다.': string;
      readonly '소셜 로그인 시': string;
      readonly '수집 시점': string;
      readonly 수탁자: string;
      readonly '시행일: 2026-05-29': string;
      readonly '업로드 PDF (OCI), AI 처리용 임시 파일 (GCS)': string;
      readonly '업로드 PDF, prompt': string;
      readonly '업로드 파일(PDF/PPT/DOCX), 커스텀 지시사항, 생성한 퀴즈, 풀이 기록, 답변, 게시글·댓글': string;
      readonly 연락처: string;
      readonly '원본 파일·이미지 저장': string;
      readonly '위탁 업무': string;
      readonly '위탁 항목': string;
      readonly '이용자 삭제 또는 회원 탈퇴 시까지': string;
      readonly '이용자 활동': string;
      readonly '이용자가 Google·Kakao 소셜 로그인을 통해 가입·로그인하는 경우, 서비스는 해당 제공자로부터 Provider ID를 전달받습니다. 각 제공자의 개인정보 정책은 해당 사이트를 참고하시기 바랍니다.': string;
      readonly '이용자는 개인정보 열람·정정·삭제·처리정지·동의 철회 권리를 행사할 수 있습니다. 닉네임 변경 및 일부 데이터 삭제는 서비스 내에서 직접 수행 가능하며, 그 외 권리 행사는 contact@q-asker.com 으로 요청해 주시기 바랍니다.': string;
      readonly '자동 수집': string;
      readonly '최대 1일': string;
      readonly '최대 90일 (운영·보안 목적)': string;
      readonly '탈퇴 시 회원 계정과 콘텐츠(퀴즈 세트, 풀이 기록, 게시글)가 삭제됩니다.': string;
      readonly '풀이 기록, 게시글': string;
      readonly '풀이 기록·게시글은 서비스 내에서 이용자가 직접 삭제할 수 있습니다.': string;
      readonly 항목: string;
      readonly 홈으로: string;
      readonly '회원 계정, 퀴즈 세트': string;
      readonly '회원 식별 및 서비스 제공 (OAuth 인증, 이용자별 퀴즈 기록 관리)': string;
      readonly '회원 정보': string;
      readonly '회원 탈퇴 시까지': string;
      readonly '회원 탈퇴는 contact@q-asker.com 으로 요청하며, 영업일 기준 7일 이내 처리됩니다.': string;
    };
    readonly ko: {
      readonly '1. 수집하는 개인정보 항목': string;
      readonly '10. 개인정보 문의': string;
      readonly '11. 권익 침해 구제': string;
      readonly '12. 처리방침 변경': string;
      readonly '2. 개인정보의 이용 목적': string;
      readonly '3. 보관·이용 기간': string;
      readonly '4. 회원 탈퇴 및 삭제 요청': string;
      readonly '5. 개인정보의 제3자 제공': string;
      readonly '6. 개인정보 처리의 위탁': string;
      readonly '7. 정보주체의 권리·의무 및 행사 방법': string;
      readonly '8. 개인정보의 안전성 확보 조치': string;
      readonly '9. 만 14세 미만 아동': string;
      readonly 'AI 추론 (Vertex AI/Gemini), 임시 파일 저장 (GCS)': string;
      readonly 'AI 퀴즈 생성 기능 제공': string;
      readonly 'AI 호출 로그': string;
      readonly 'AI 호출 로그, 서술형 채점 로그': string;
      readonly 'AI 호출 시 자동': string;
      readonly 'CDN·DDoS 보호': string;
      readonly 'Cloudflare, Inc.': string;
      readonly 'Google LLC': string;
      readonly 'IP 주소': string;
      readonly 'IP 주소, 접속 로그': string;
      readonly 'IP·접속 로그': string;
      readonly 'OAuth Provider ID': string;
      readonly 'Oracle Cloud (OCI)': string;
      readonly 'PDF, 이미지': string;
      readonly 'Provider ID, prompt, AI 응답, 모델·토큰·응답시간': string;
      readonly 'Q-Asker(이하 "서비스")는 「개인정보보호법」을 준수하며, 이용자의 개인정보를 안전하게 보호하기 위해 본 처리방침을 수립·공개합니다.': string;
      readonly '개인정보 분쟁조정위원회 (kopico.go.kr / 1833-6972)': string;
      readonly '개인정보 처리방침': string;
      readonly '개인정보 침해신고센터 (privacy.kisa.or.kr / 118)': string;
      readonly '개인정보 침해에 대한 분쟁 조정·상담은 다음 기관에 신청할 수 있습니다.': string;
      readonly '고객 문의 응대': string;
      readonly 구분: string;
      readonly '모든 요청 시': string;
      readonly 목차: string;
      readonly '법령에 따라 보관이 요구되는 경우 해당 기간 동안 분리 보관 후 파기합니다.': string;
      readonly '보관 기간': string;
      readonly '본 처리방침은 법령·정책 변경에 따라 개정될 수 있으며, 변경 시 시행일 7일 전(이용자에게 불리한 변경은 30일 전) 서비스 내 공지합니다. 단, 이용자에게 편익을 주는 변경 또는 긴급한 법령·보안 대응이 필요한 경우에는 즉시 시행될 수 있습니다.': string;
      readonly '부정 이용 방지·보안 (Rate Limiting, 어뷰징 감지)': string;
      readonly '서비스 이용 시': string;
      readonly '서비스 품질 개선·운영 (오류 추적, 성능 분석)': string;
      readonly '서비스는 HTTPS(TLS) 암호화 통신, JWT 기반 접근 제어, DB 민감 설정값 Jasypt 암호화, Bucket4j 기반 Rate Limiting, Cloudflare/OCI 방화벽을 통해 개인정보를 보호합니다. 처리 담당자는 최소화하며 접근 권한은 역할 기반으로 관리합니다.': string;
      readonly '서비스는 「개인정보보호법」 제26조에 따라 수탁자의 안전한 처리를 관리·감독합니다.': string;
      readonly '서비스는 만 14세 이상을 서비스 대상으로 합니다. 만 14세 미만의 가입은 제한되며, 법정대리인 동의 없이 수집된 사실이 확인되면 즉시 삭제합니다.': string;
      readonly '서비스는 원칙적으로 개인정보를 제3자에게 제공하지 않습니다. 다만 이용자가 사전 동의한 경우 또는 법령에 따른 적법한 요청이 있는 경우 예외로 합니다.': string;
      readonly '서비스는 위 목적 외 용도(특히 AI 모델 학습, 마케팅, 제3자 판매)로 개인정보를 이용하지 않습니다.': string;
      readonly '소셜 로그인 시': string;
      readonly '수집 시점': string;
      readonly 수탁자: string;
      readonly '시행일: 2026-05-29': string;
      readonly '업로드 PDF (OCI), AI 처리용 임시 파일 (GCS)': string;
      readonly '업로드 PDF, prompt': string;
      readonly '업로드 파일(PDF/PPT/DOCX), 커스텀 지시사항, 생성한 퀴즈, 풀이 기록, 답변, 게시글·댓글': string;
      readonly 연락처: string;
      readonly '원본 파일·이미지 저장': string;
      readonly '위탁 업무': string;
      readonly '위탁 항목': string;
      readonly '이용자 삭제 또는 회원 탈퇴 시까지': string;
      readonly '이용자 활동': string;
      readonly '이용자가 Google·Kakao 소셜 로그인을 통해 가입·로그인하는 경우, 서비스는 해당 제공자로부터 Provider ID를 전달받습니다. 각 제공자의 개인정보 정책은 해당 사이트를 참고하시기 바랍니다.': string;
      readonly '이용자는 개인정보 열람·정정·삭제·처리정지·동의 철회 권리를 행사할 수 있습니다. 닉네임 변경 및 일부 데이터 삭제는 서비스 내에서 직접 수행 가능하며, 그 외 권리 행사는 contact@q-asker.com 으로 요청해 주시기 바랍니다.': string;
      readonly '자동 수집': string;
      readonly '최대 1일': string;
      readonly '최대 90일 (운영·보안 목적)': string;
      readonly '탈퇴 시 회원 계정과 콘텐츠(퀴즈 세트, 풀이 기록, 게시글)가 삭제됩니다.': string;
      readonly '풀이 기록, 게시글': string;
      readonly '풀이 기록·게시글은 서비스 내에서 이용자가 직접 삭제할 수 있습니다.': string;
      readonly 항목: string;
      readonly 홈으로: string;
      readonly '회원 계정, 퀴즈 세트': string;
      readonly '회원 식별 및 서비스 제공 (OAuth 인증, 이용자별 퀴즈 기록 관리)': string;
      readonly '회원 정보': string;
      readonly '회원 탈퇴 시까지': string;
      readonly '회원 탈퇴는 contact@q-asker.com 으로 요청하며, 영업일 기준 7일 이내 처리됩니다.': string;
    };
  };
  readonly 'quiz-explanation': {
    readonly en: {
      readonly 'AI 피드백': string;
      readonly 'PDF 로딩 중...': string;
      readonly 검토함: string;
      readonly '내 답변': string;
      readonly '내 답안': string;
      readonly 다음: string;
      readonly 모범답안: string;
      readonly 미답안: string;
      readonly 슬라이드의: string;
      readonly 오답만: string;
      readonly '원본 PDF 열기': string;
      readonly 이전: string;
      readonly 점: string;
      readonly 정답: string;
      readonly '참조 자료': string;
      readonly '파일 링크가 만료되었습니다.': string;
      readonly '파일이 존재하지 않습니다.': string;
      readonly 페이지: string;
      readonly 해설: string;
      readonly '현재는 pdf 파일만 지원합니다.': string;
      readonly 홈으로: string;
    };
    readonly ko: {
      readonly 'AI 피드백': string;
      readonly 'PDF 로딩 중...': string;
      readonly 검토함: string;
      readonly '내 답변': string;
      readonly '내 답안': string;
      readonly 다음: string;
      readonly 모범답안: string;
      readonly 미답안: string;
      readonly 슬라이드의: string;
      readonly 오답만: string;
      readonly '원본 PDF 열기': string;
      readonly 이전: string;
      readonly 점: string;
      readonly 정답: string;
      readonly '참조 자료': string;
      readonly '파일 링크가 만료되었습니다.': string;
      readonly '파일이 존재하지 않습니다.': string;
      readonly 페이지: string;
      readonly 해설: string;
      readonly '현재는 pdf 파일만 지원합니다.': string;
      readonly 홈으로: string;
    };
  };
  readonly 'quiz-history': {
    readonly en: {
      readonly '내 퀴즈 기록': string;
      readonly '다시 풀기': string;
      readonly '로그인이 필요한 서비스입니다': string;
      readonly 로그인하기: string;
      readonly 만들기: string;
      readonly 문제: string;
      readonly 미분류: string;
      readonly '미분류 기록이 없습니다.': string;
      readonly '미분류로 빼기': string;
      readonly 미완료: string;
      readonly 삭제: string;
      readonly 상태: string;
      readonly '새 폴더': string;
      readonly 생성일: string;
      readonly '아직 만든 퀴즈가 없습니다': string;
      readonly '아직 만든 폴더가 없습니다. 새 폴더를 만들어보세요.': string;
      readonly 액션: string;
      readonly 완료: string;
      readonly 완료율: string;
      readonly 완료일: string;
      readonly '완료한 퀴즈': string;
      readonly '이 폴더에 기록이 없습니다.': string;
      readonly 저장: string;
      readonly 전체: string;
      readonly '전체 삭제': string;
      readonly 점: string;
      readonly 점수: string;
      readonly 제목: string;
      readonly '지금까지 만들고 푼 퀴즈들을 확인해보세요': string;
      readonly '총 퀴즈 수': string;
      readonly 취소: string;
      readonly '퀴즈 기록은 로그인 후에 확인할 수 있습니다.': string;
      readonly '퀴즈 만들기': string;
      readonly '퀴즈 유형': string;
      readonly '퀴즈 풀기': string;
      readonly '퀴즈를 만들어서 문제를 풀어보세요!': string;
      readonly '평균 점수': string;
      readonly '폴더 삭제': string;
      readonly '폴더 이름': string;
      readonly '폴더 이름 변경': string;
      readonly '폴더 이름을 입력하세요.': string;
      readonly '폴더로 이동': string;
    };
    readonly ko: {
      readonly '내 퀴즈 기록': string;
      readonly '다시 풀기': string;
      readonly '로그인이 필요한 서비스입니다': string;
      readonly 로그인하기: string;
      readonly 만들기: string;
      readonly 문제: string;
      readonly 미분류: string;
      readonly '미분류 기록이 없습니다.': string;
      readonly '미분류로 빼기': string;
      readonly 미완료: string;
      readonly 삭제: string;
      readonly 상태: string;
      readonly '새 폴더': string;
      readonly 생성일: string;
      readonly '아직 만든 퀴즈가 없습니다': string;
      readonly '아직 만든 폴더가 없습니다. 새 폴더를 만들어보세요.': string;
      readonly 액션: string;
      readonly 완료: string;
      readonly 완료율: string;
      readonly 완료일: string;
      readonly '완료한 퀴즈': string;
      readonly '이 폴더에 기록이 없습니다.': string;
      readonly 저장: string;
      readonly 전체: string;
      readonly '전체 삭제': string;
      readonly 점: string;
      readonly 점수: string;
      readonly 제목: string;
      readonly '지금까지 만들고 푼 퀴즈들을 확인해보세요': string;
      readonly '총 퀴즈 수': string;
      readonly 취소: string;
      readonly '퀴즈 기록은 로그인 후에 확인할 수 있습니다.': string;
      readonly '퀴즈 만들기': string;
      readonly '퀴즈 유형': string;
      readonly '퀴즈 풀기': string;
      readonly '퀴즈를 만들어서 문제를 풀어보세요!': string;
      readonly '평균 점수': string;
      readonly '폴더 삭제': string;
      readonly '폴더 이름': string;
      readonly '폴더 이름 변경': string;
      readonly '폴더 이름을 입력하세요.': string;
      readonly '폴더로 이동': string;
    };
  };
  readonly 'quiz-history-detail': {
    readonly en: {
      readonly '기록을 불러오는데 실패했습니다.': string;
      readonly '내 답변': string;
      readonly 모범답안: string;
      readonly 목록으로: string;
      readonly '부분 정답': string;
      readonly 점: string;
      readonly 정답: string;
      readonly 총점: string;
      readonly '해설 보기': string;
    };
    readonly ko: {
      readonly '기록을 불러오는데 실패했습니다.': string;
      readonly '내 답변': string;
      readonly 모범답안: string;
      readonly 목록으로: string;
      readonly '부분 정답': string;
      readonly 점: string;
      readonly 정답: string;
      readonly 총점: string;
      readonly '해설 보기': string;
    };
  };
  readonly 'quiz-result': {
    readonly en: {
      readonly '내 답변': string;
      readonly 모범답안: string;
      readonly '문제 미채점': string;
      readonly 미채점: string;
      readonly '부분 정답': string;
      readonly 점: string;
      readonly 정답: string;
      readonly '채점하지 않고 제출되었습니다': string;
      readonly 총점: string;
      readonly '해설 보기': string;
      readonly 홈으로: string;
    };
    readonly ko: {
      readonly '내 답변': string;
      readonly 모범답안: string;
      readonly '문제 미채점': string;
      readonly 미채점: string;
      readonly '부분 정답': string;
      readonly 점: string;
      readonly 정답: string;
      readonly '채점하지 않고 제출되었습니다': string;
      readonly 총점: string;
      readonly '해설 보기': string;
      readonly 홈으로: string;
    };
  };
  readonly 'solve-quiz': {
    readonly en: {
      readonly 'AI 지시사항 반영 결과': string;
      readonly '{{n}}번째 빈칸': string;
      readonly '{{n}}번째 빈칸을 클릭하여 답 입력': string;
      readonly '{{n}}번째 빈칸의 답을 입력하세요': string;
      readonly '{{quizItem_userAnswer}}번': string;
      readonly 개: string;
      readonly 검토: string;
      readonly '검토할 문제:': string;
      readonly '다시 채점하기': string;
      readonly 다음: string;
      readonly 닫기: string;
      readonly '답변을 입력하세요': string;
      readonly '답변한 문제:': string;
      readonly '답을 직접 입력하세요': string;
      readonly '로그인 후 이어서 풀 수 있습니다.': string;
      readonly '로그인하고 기록하기': string;
      readonly '문제 목록': string;
      readonly 미선택: string;
      readonly '번:': string;
      readonly '베타 버전입니다! 건의사항 / 피드백 있으면 부탁드립니다!': string;
      readonly '불편한 점이나 개선 아이디어를 자유롭게 남겨주세요.': string;
      readonly '빈칸을 클릭하여 답 입력': string;
      readonly '선택지 보기': string;
      readonly '선택지 숨기기': string;
      readonly '소중한 의견 감사합니다!': string;
      readonly 시도: string;
      readonly '시도에 따라 단계별 힌트가 제시됩니다!': string;
      readonly '안푼 문제:': string;
      readonly 이전: string;
      readonly '입력한 답안': string;
      readonly 전송: string;
      readonly '전송 중...': string;
      readonly '전송에 실패했습니다. 다시 시도해주세요.': string;
      readonly '전체 문제:': string;
      readonly 점: string;
      readonly '제출 확인': string;
      readonly 제출하기: string;
      readonly '진행 상태가 저장되었습니다.': string;
      readonly '진행 현황': string;
      readonly 진행률: string;
      readonly '채점 실패': string;
      readonly '채점 중...': string;
      readonly 채점하기: string;
      readonly '추가 피드백 작성': string;
      readonly 취소: string;
      readonly '퀴즈 기록 중': string;
      readonly 확인: string;
    };
    readonly ko: {
      readonly 'AI 지시사항 반영 결과': string;
      readonly '{{n}}번째 빈칸': string;
      readonly '{{n}}번째 빈칸을 클릭하여 답 입력': string;
      readonly '{{n}}번째 빈칸의 답을 입력하세요': string;
      readonly '{{quizItem_userAnswer}}번': string;
      readonly 개: string;
      readonly 검토: string;
      readonly '검토할 문제:': string;
      readonly '다시 채점하기': string;
      readonly 다음: string;
      readonly 닫기: string;
      readonly '답변을 입력하세요': string;
      readonly '답변한 문제:': string;
      readonly '답을 직접 입력하세요': string;
      readonly '로그인 후 이어서 풀 수 있습니다.': string;
      readonly '로그인하고 기록하기': string;
      readonly '문제 목록': string;
      readonly 미선택: string;
      readonly '번:': string;
      readonly '베타 버전입니다! 건의사항 / 피드백 있으면 부탁드립니다!': string;
      readonly '불편한 점이나 개선 아이디어를 자유롭게 남겨주세요.': string;
      readonly '빈칸을 클릭하여 답 입력': string;
      readonly '선택지 보기': string;
      readonly '선택지 숨기기': string;
      readonly '소중한 의견 감사합니다!': string;
      readonly 시도: string;
      readonly '시도에 따라 단계별 힌트가 제시됩니다!': string;
      readonly '안푼 문제:': string;
      readonly 이전: string;
      readonly '입력한 답안': string;
      readonly 전송: string;
      readonly '전송 중...': string;
      readonly '전송에 실패했습니다. 다시 시도해주세요.': string;
      readonly '전체 문제:': string;
      readonly 점: string;
      readonly '제출 확인': string;
      readonly 제출하기: string;
      readonly '진행 상태가 저장되었습니다.': string;
      readonly '진행 현황': string;
      readonly 진행률: string;
      readonly '채점 실패': string;
      readonly '채점 중...': string;
      readonly 채점하기: string;
      readonly '추가 피드백 작성': string;
      readonly 취소: string;
      readonly '퀴즈 기록 중': string;
      readonly 확인: string;
    };
  };
  readonly 'terms-of-service': {
    readonly en: {
      readonly '1. 서비스 소개': string;
      readonly '2. 회원가입 및 계정': string;
      readonly '3. 회원 탈퇴': string;
      readonly '4. 이용자의 의무': string;
      readonly '5. 파일 및 콘텐츠': string;
      readonly '6. AI 생성 결과의 특성': string;
      readonly '7. 서비스 제공·변경·중단 및 면책': string;
      readonly '8. 약관 변경 및 분쟁 해결': string;
      readonly '9. 문의처': string;
      readonly 'AI 생성 결과의 상업적 재판매·무단 대량 배포': string;
      readonly 'Q-Asker(이하 "서비스")를 이용해 주셔서 감사합니다. 본 약관은 서비스 이용 조건을 규정합니다.': string;
      readonly 'Q-Asker는 소셜 로그인만 지원합니다.': string;
      readonly 'Q-Asker는 학습 자료를 업로드하면 AI가 자동으로 다양한 유형의 퀴즈를 생성하는 무료 웹 서비스입니다. 회원가입 없이 이용 가능하며, 로그인 시 풀이 기록 저장 등의 기능이 제공됩니다.': string;
      readonly '닉네임은 이용자가 변경할 수 있으며, 타인 사칭·욕설·혐오 표현은 서비스가 제한·변경할 수 있습니다.': string;
      readonly '동일 자료에서도 호출마다 결과가 다를 수 있습니다.': string;
      readonly 목차: string;
      readonly '무료로 제공되는 본 서비스의 이용으로 인한 직접·간접·부수적 손해에 대해 서비스의 고의 또는 중대한 과실이 없는 한 책임을 부담하지 않습니다.': string;
      readonly '본 서비스는 만 14세 이상을 대상으로 합니다.': string;
      readonly '본 약관은 대한민국 법률에 따라 해석되며, 분쟁은 대한민국 법원을 관할로 합니다.': string;
      readonly '본 약관은 변경 시 시행일 7일 전(이용자에게 불리한 변경은 30일 전) 서비스 내 공지합니다. 단, 이용자에게 편익을 주는 변경 또는 긴급한 법령·보안 대응이 필요한 경우에는 즉시 시행될 수 있습니다.': string;
      readonly '사실 오류·편향·누락이 있을 수 있으므로 학습 보조 도구로만 활용하고, 중요한 용도(시험·평가 등)에는 반드시 직접 검증해야 합니다.': string;
      readonly '서비스 이용약관': string;
      readonly '서비스는 사전 고지 없이 서비스 일부 또는 전부의 기능을 변경·중단할 수 있습니다.': string;
      readonly '서비스를 불법·비윤리적 목적으로 사용': string;
      readonly '시행일 이후 이용을 계속하면 변경에 동의한 것으로 간주합니다.': string;
      readonly '시행일: 2026-05-29': string;
      readonly '업로드한 파일은 퀴즈 생성 목적으로만 처리되며, AI 학습 데이터로 사용되지 않습니다.': string;
      readonly '외부 서비스(Google Gemini, OCI, GCS, Cloudflare 등)의 장애·정책 변경, 천재지변, 시스템 장애로 인한 손해에 대해 서비스는 책임지지 않습니다.': string;
      readonly '위반 시 서비스는 사전 통지 없이 이용을 제한·정지하거나 계정을 삭제할 수 있습니다.': string;
      readonly '음란·폭력·차별·혐오 콘텐츠 생성·게시': string;
      readonly '이메일: contact@q-asker.com': string;
      readonly '이용자는 다음 행위를 하지 않아야 합니다.': string;
      readonly '자동화된 수단(크롤러, 봇, 스크립트)으로 접근하거나 Rate Limit을 우회하는 행위': string;
      readonly '저작권 침해 신고는 문의처로 접수해 주시기 바랍니다.': string;
      readonly '퀴즈는 Google Gemini의 추론 결과이며, 서비스는 정확성·완전성을 보장하지 않습니다.': string;
      readonly '타 이용자의 계정·기록을 무단 조회·변경하려는 시도': string;
      readonly '타인의 저작권·초상권·상표권을 침해하는 파일 업로드': string;
      readonly '파일은 최대 1일 후 자동 삭제됩니다.': string;
      readonly '파일의 저작권은 이용자에게 있으며, 서비스는 위 목적 범위 내 일시적 이용권만 가집니다.': string;
      readonly 홈으로: string;
      readonly '회원 탈퇴는 contact@q-asker.com 으로 요청하며, 영업일 기준 7일 이내 처리됩니다.': string;
    };
    readonly ko: {
      readonly '1. 서비스 소개': string;
      readonly '2. 회원가입 및 계정': string;
      readonly '3. 회원 탈퇴': string;
      readonly '4. 이용자의 의무': string;
      readonly '5. 파일 및 콘텐츠': string;
      readonly '6. AI 생성 결과의 특성': string;
      readonly '7. 서비스 제공·변경·중단 및 면책': string;
      readonly '8. 약관 변경 및 분쟁 해결': string;
      readonly '9. 문의처': string;
      readonly 'AI 생성 결과의 상업적 재판매·무단 대량 배포': string;
      readonly 'Q-Asker(이하 "서비스")를 이용해 주셔서 감사합니다. 본 약관은 서비스 이용 조건을 규정합니다.': string;
      readonly 'Q-Asker는 소셜 로그인만 지원합니다.': string;
      readonly 'Q-Asker는 학습 자료를 업로드하면 AI가 자동으로 다양한 유형의 퀴즈를 생성하는 무료 웹 서비스입니다. 회원가입 없이 이용 가능하며, 로그인 시 풀이 기록 저장 등의 기능이 제공됩니다.': string;
      readonly '닉네임은 이용자가 변경할 수 있으며, 타인 사칭·욕설·혐오 표현은 서비스가 제한·변경할 수 있습니다.': string;
      readonly '동일 자료에서도 호출마다 결과가 다를 수 있습니다.': string;
      readonly 목차: string;
      readonly '무료로 제공되는 본 서비스의 이용으로 인한 직접·간접·부수적 손해에 대해 서비스의 고의 또는 중대한 과실이 없는 한 책임을 부담하지 않습니다.': string;
      readonly '본 서비스는 만 14세 이상을 대상으로 합니다.': string;
      readonly '본 약관은 대한민국 법률에 따라 해석되며, 분쟁은 대한민국 법원을 관할로 합니다.': string;
      readonly '본 약관은 변경 시 시행일 7일 전(이용자에게 불리한 변경은 30일 전) 서비스 내 공지합니다. 단, 이용자에게 편익을 주는 변경 또는 긴급한 법령·보안 대응이 필요한 경우에는 즉시 시행될 수 있습니다.': string;
      readonly '사실 오류·편향·누락이 있을 수 있으므로 학습 보조 도구로만 활용하고, 중요한 용도(시험·평가 등)에는 반드시 직접 검증해야 합니다.': string;
      readonly '서비스 이용약관': string;
      readonly '서비스는 사전 고지 없이 서비스 일부 또는 전부의 기능을 변경·중단할 수 있습니다.': string;
      readonly '서비스를 불법·비윤리적 목적으로 사용': string;
      readonly '시행일 이후 이용을 계속하면 변경에 동의한 것으로 간주합니다.': string;
      readonly '시행일: 2026-05-29': string;
      readonly '업로드한 파일은 퀴즈 생성 목적으로만 처리되며, AI 학습 데이터로 사용되지 않습니다.': string;
      readonly '외부 서비스(Google Gemini, OCI, GCS, Cloudflare 등)의 장애·정책 변경, 천재지변, 시스템 장애로 인한 손해에 대해 서비스는 책임지지 않습니다.': string;
      readonly '위반 시 서비스는 사전 통지 없이 이용을 제한·정지하거나 계정을 삭제할 수 있습니다.': string;
      readonly '음란·폭력·차별·혐오 콘텐츠 생성·게시': string;
      readonly '이메일: contact@q-asker.com': string;
      readonly '이용자는 다음 행위를 하지 않아야 합니다.': string;
      readonly '자동화된 수단(크롤러, 봇, 스크립트)으로 접근하거나 Rate Limit을 우회하는 행위': string;
      readonly '저작권 침해 신고는 문의처로 접수해 주시기 바랍니다.': string;
      readonly '퀴즈는 Google Gemini의 추론 결과이며, 서비스는 정확성·완전성을 보장하지 않습니다.': string;
      readonly '타 이용자의 계정·기록을 무단 조회·변경하려는 시도': string;
      readonly '타인의 저작권·초상권·상표권을 침해하는 파일 업로드': string;
      readonly '파일은 최대 1일 후 자동 삭제됩니다.': string;
      readonly '파일의 저작권은 이용자에게 있으며, 서비스는 위 목적 범위 내 일시적 이용권만 가집니다.': string;
      readonly 홈으로: string;
      readonly '회원 탈퇴는 contact@q-asker.com 으로 요청하며, 영업일 기준 7일 이내 처리됩니다.': string;
    };
  };
};

export type I18nexusGeneratedNamespace = keyof I18nexusGeneratedTranslations & string;

export type I18nexusGeneratedTranslationKeys<
  NS extends I18nexusGeneratedNamespace = I18nexusGeneratedNamespace,
> = TranslationKeys[NS] | CommonKeys;

export type I18nexusGeneratedServerTranslationFunction<
  NS extends I18nexusGeneratedNamespace = I18nexusGeneratedNamespace,
> = (
  key: I18nexusGeneratedTranslationKeys<NS>,
  variables?: Record<string, string | number>,
  fallback?: string,
) => string;

export type I18nexusGeneratedClientTranslationFunction<
  NS extends I18nexusGeneratedNamespace = I18nexusGeneratedNamespace,
> = (
  key: I18nexusGeneratedTranslationKeys<NS>,
  variables?: Record<string, string | number>,
) => string;

export type I18nexusGeneratedTranslationFunction<
  NS extends I18nexusGeneratedNamespace = I18nexusGeneratedNamespace,
> = I18nexusGeneratedServerTranslationFunction<NS>;
// ============================================
// Module Augmentation
// ============================================

import type { UseTranslationReturn } from 'i18nexus';
import type { GetTranslationReturn, GetTranslationOptions } from 'i18nexus/server';

declare module 'i18nexus' {
  /**
   * Type-safe translation hook (Client Component)
   *
   * @template NS - The namespace to use
   * @param namespace - The namespace string
   * @returns Translation utilities with type-safe keys
   *
   * Note: Keys from the fallback namespace "common" are automatically included.
   *
   * @example
   * ```tsx
   * const { t } = useTranslation<"home">("home");
   * t("title");  // ✅ OK (from home namespace)
   * t("common-key");  // ✅ OK (from fallback namespace)
   * t("typo");   // ❌ Compile error!
   * ```
   */
  export function useTranslation<NS extends TranslationNamespace = TranslationNamespace>(
    namespace: NS,
  ): UseTranslationReturn<TranslationKeys[NS] | CommonKeys>;

  // Individual namespace key types (for use in constants and type definitions)
  export type CommonKeys = TranslationKeys['common'];
  export type BoardKeys = TranslationKeys['board'];
  export type BoardDetailKeys = TranslationKeys['board-detail'];
  export type BoardWriteKeys = TranslationKeys['board-write'];
  export type LoginRedirectKeys = TranslationKeys['login-redirect'];
  export type LoginSelectKeys = TranslationKeys['login-select'];
  export type MaintenanceKeys = TranslationKeys['maintenance'];
  export type MakeQuizKeys = TranslationKeys['make-quiz'];
  export type PrivacyPolicyKeys = TranslationKeys['privacy-policy'];
  export type QuizExplanationKeys = TranslationKeys['quiz-explanation'];
  export type QuizHistoryKeys = TranslationKeys['quiz-history'];
  export type QuizHistoryDetailKeys = TranslationKeys['quiz-history-detail'];
  export type QuizResultKeys = TranslationKeys['quiz-result'];
  export type SolveQuizKeys = TranslationKeys['solve-quiz'];
  export type TermsOfServiceKeys = TranslationKeys['terms-of-service'];
}

declare module 'i18nexus/server' {
  /**
   * Type-safe translation function (Server Component)
   *
   * @template NS - The namespace to use
   * @param namespace - The namespace string (optional, auto-inferred)
   * @param options - Optional configuration
   * @returns Translation utilities with type-safe keys
   *
   * @example
   * ```tsx
   * const { t } = await getTranslation<"home">("home");
   * t("title");  // ✅ OK
   * t("typo");   // ❌ Compile error!
   * ```
   */
  export function getTranslation<NS extends TranslationNamespace = TranslationNamespace>(
    namespace?: NS,
    options?: GetTranslationOptions,
  ): Promise<GetTranslationReturn<NS, TranslationKeys[NS] | CommonKeys>>;
}
