/**
 * Auto-generated TypeScript type definitions for i18nexus
 *
 * DO NOT EDIT THIS FILE MANUALLY!
 * Run 'npx i18n-extractor' to regenerate.
 *
 * @generated by i18nexus-tools
 */

// ============================================
// Global Translation Types
// ============================================

/**
 * All available translation namespaces
 *
 * @example "home" | "about" | "common"
 */
declare type TranslationNamespace =
  | 'board'
  | 'board-detail'
  | 'board-write'
  | 'common'
  | 'login-redirect'
  | 'login-select'
  | 'maintenance'
  | 'make-quiz'
  | 'privacy-policy'
  | 'quiz-explanation'
  | 'quiz-history'
  | 'quiz-history-detail'
  | 'quiz-result'
  | 'solve-quiz';

declare type BoardKeys =
  | '건'
  | '게시글 목록을 불러올 수 없습니다.'
  | '답변완료'
  | '대기중'
  | '데이터를 불러오는데 실패했습니다.'
  | '로그인이 필요한 서비스입니다.\n로그인 페이지로 이동하시겠습니까?'
  | '문의 게시판'
  | '문의 작성하기'
  | '문의하기'
  | '상태'
  | '아직 등록된 문의가 없습니다'
  | '작성일'
  | '작성자'
  | '제목'
  | '조회'
  | '총';

declare type BoardDetailKeys =
  | '개인정보가 포함되지 않도록 주의하세요.'
  | '건'
  | '게시글이 삭제되었습니다.'
  | '관리자'
  | '관리자 답변'
  | '관리자 답변 작성'
  | '글 내용을 입력해주세요.'
  | '답변 #'
  | '답변 ('
  | '답변 내용을 입력하세요.'
  | '답변 등록'
  | '답변 등록 후 사용자에게 알림이 전송됩니다.'
  | '답변 작성'
  | '답변완료'
  | '답변을 입력하세요...'
  | '대기중'
  | '댓글'
  | '댓글 {{expr0}}건'
  | '댓글이 등록되었습니다.'
  | '등록'
  | '등록 중...'
  | '로딩 중...'
  | '목록'
  | '목록으로'
  | '문의 게시판'
  | '사용자 문의에 대한 답변 내용을 입력하세요.'
  | '삭제'
  | '삭제하기'
  | '상세'
  | '상태'
  | '새 문의'
  | '새 문의하기'
  | '수정'
  | '수정하기'
  | '아직 등록된 답변이 없습니다.'
  | '아직 등록된 댓글이 없습니다.'
  | '작성일'
  | '작성자'
  | '정말로 이 게시글을 삭제하시겠습니까?'
  | '정확하고 친절한 답변을 작성해 주세요.'
  | '조회'
  | '조회수'
  | '취소';

/** Interpolation variables for "board-detail" namespace keys */
declare type BoardDetailKeyVariables = {
  '댓글 {{expr0}}건': 'expr0';
};

declare type BoardWriteKeys =
  | '내용'
  | '등록'
  | '등록 중...'
  | '등록하기'
  | '로그인이 필요합니다.'
  | '문의 내용을 상세히 적어주세요.'
  | '문의 수정'
  | '새 문의 작성'
  | '수정'
  | '수정 권한이 없습니다.'
  | '수정 중...'
  | '수정완료'
  | '제목'
  | '제목과 내용을 모두 입력해주세요.'
  | '제목을 입력해주세요'
  | '취소';

declare type CommonKeys =
  | '"문제 풀기" 버튼으로'
  | '(최대'
  | '1. 빈칸 채우기로 핵심 개념을 정리하세요.'
  | '1. 수집하는 개인정보'
  | '1단계: 파일 업로드'
  | '2. OX로 빠르게 개념을 점검하세요.'
  | '2. 개인정보의 이용 목적'
  | '20개'
  | '24시간 후 서버에서 자동 삭제'
  | '24시간 후 자동 삭제되며 별도로 저장, 공유되지 않습니다.'
  | '2단계: 퀴즈 옵션 설정'
  | '3. 객관식으로 개념을 응용해 보세요.'
  | '3. 보관 및 이용 기간'
  | '3단계: AI 문제 생성'
  | '4. 제3자 제공'
  | '4단계: 퀴즈 풀기'
  | '5 ~ 25개 (5개 단위)'
  | '5. 개인정보 처리 위탁'
  | '5단계: 결과 및 해설 확인'
  | '6. 이용자 권리'
  | '6단계: 퀴즈 기록 관리'
  | '7. 문의처'
  | 'AI 기반 자동 퀴즈 생성'
  | 'AI 분석: '
  | 'AI 퀴즈 만들기 6단계 가이드'
  | 'AI 퀴즈 생성'
  | 'AI 퀴즈 활용 200% 팁'
  | 'AI 한계점:'
  | 'AI가 만드는 나만의 퀴즈'
  | 'AI는 높은 정확도로 문서를 분석하지만, 100% 완벽하지 않을 수 있습니다. 생성된 문제는 학습 참고용이며, 중요한 정보는 반드시 원본과 교차 확인해주세요.'
  | 'OX 퀴즈'
  | 'OX: 핵심 개념의 옳고 그름을 빠르게 점검하는 문제'
  | 'PDF 로딩 중...'
  | 'PDF, PPT, Word 공부 자료로 퀴즈를 만들어 보세요. 핵심 개념을 빠르게 암기하고 시험 대비에 효과적입니다.'
  | 'Q-Asker 사용 중 궁금한 점이나 개선 아이디어가 있으시면 언제든지 알려주세요! 더 좋은'
  | 'Q-Asker 이메일 문의'
  | 'Q-Asker(이하 "서비스")는 이용자의 개인정보를 소중히 보호하며 관련 법령을 준수합니다.'
  | 'Q-Asker: PDF, PPT, Word로 무료 AI 퀴즈 생성'
  | 'Q-Asker를 신뢰할 수 있는 이유'
  | 'Q. AI가 만든 퀴즈의 정확도는 어느 정도인가요?'
  | 'Q. Q-Asker는 정말 무료인가요?'
  | 'Q. 업로드한 제 파일은 안전하게 관리되나요?'
  | 'Q. 이미지로 된 파일도 퀴즈로 만들 수 있나요?'
  | '{{quizItem_userAnswer}}번'
  | '가지고 계신 학습 자료로 AI 퀴즈를 만드는 가장 쉬운 방법을 알려드립니다.'
  | '개'
  | '개인정보 열람, 정정, 삭제를 요청할 수 있습니다.'
  | '개인정보 처리방침'
  | '개인정보가 포함되지 않도록 주의하세요.'
  | '객관식'
  | '객관식: 개념을 비교·분석하고 적용하는 문제'
  | '건'
  | '걸린 시간'
  | '검토'
  | '검토 기능: '
  | '검토할 문제:'
  | '게시글 목록을 불러올 수 없습니다.'
  | '게시글 삭제 중 오류가 발생했습니다.'
  | '게시글 정보를 확인할 수 없습니다.'
  | '게시글을 불러올 권한이 없거나 삭제된 게시글입니다.'
  | '게시글이 삭제되었습니다.'
  | '결과 확인: '
  | '관리자'
  | '관리자 답변'
  | '관리자 답변 작성'
  | '광주'
  | '구글 로그인'
  | '구글 폼 링크'
  | '구글 폼:'
  | '그 외 정보는 목적 달성 시 지체 없이 파기합니다.'
  | '글 내용을 입력해주세요.'
  | '기록 삭제 실패:'
  | '기록 삭제:'
  | '기록 삭제에 실패했습니다.'
  | '기록을 불러오는데 실패했습니다.'
  | '기록이 삭제되었습니다.'
  | '까지 자동으로 저장됩니다'
  | '꼭 읽어주세요: 주의사항'
  | '나중에 다시 볼 문제에 체크 표시'
  | '난이도'
  | '내 퀴즈 기록'
  | '내용'
  | '네, PDF, PPT, Word 기반 AI 퀴즈 생성은 현재 완전 무료입니다. 별도의 회원가입 없이 누구나 자유롭게 이용할 수 있습니다.'
  | '네. OCR을 지원하여 스캔 본이나 사진 형태의 문서도 분석할 수 있습니다.'
  | '네. 업로드된 파일은 퀴즈 생성을 위해서만 일시적으로 사용되며, 24시간 뒤에 삭제됩니다.'
  | '네비게이션: '
  | '다른 문제 생성'
  | '다른 파일 넣기'
  | '다만, 법령에 따라 요청되는 경우 제공될 수 있습니다.'
  | '다시 로그인해주세요.'
  | '다시 풀기'
  | '다양한 파일 형식 지원'
  | '다음'
  | '닫기'
  | '답변 #'
  | '답변 ('
  | '답변 내용을 입력하세요.'
  | '답변 등록'
  | '답변 등록 후 사용자에게 알림이 전송됩니다.'
  | '답변 작성'
  | '답변완료'
  | '답변을 입력하세요...'
  | '답변한 문제:'
  | '대구'
  | '대기중'
  | '댓글'
  | '댓글 {{expr0}}건'
  | '댓글 등록 중 오류가 발생했습니다.'
  | '댓글을 작성할 권한이 없습니다.'
  | '댓글이 등록되었습니다.'
  | '더 나은 서비스를 위해 시스템을 점검하고 있습니다.'
  | '더 많은 페이지 로딩 중... ('
  | '데이터를 불러오는데 실패했습니다.'
  | '도움말 보기'
  | '되어 해설을 볼 수\n              없게 됩니다'
  | '등록'
  | '등록 중...'
  | '등록하기'
  | '또는'
  | '로그아웃'
  | '로그아웃되었습니다.'
  | '로그아웃에 실패했습니다.'
  | '로그인'
  | '로그인 리다이렉트 실패:'
  | '로그인 시 서비스 이용약관에 동의하게 됩니다.'
  | '로그인 처리 중...'
  | '로그인에 실패했습니다. 다시 로그인해주세요.'
  | '로그인에 실패했습니다. 다시 시도해주세요.'
  | '로그인이 필요한 서비스입니다'
  | '로그인이 필요한 서비스입니다.\n로그인 페이지로 이동하시겠습니까?'
  | '로그인이 필요합니다.'
  | '로그인하고, 퀴즈기록을 저장해보세요'
  | '로그인하기'
  | '로딩 중...'
  | '마지막 문제입니다.'
  | '만든 퀴즈가 퀴즈 기록에 자동 저장'
  | '메뉴'
  | '명확한 문제 생성 기준'
  | '모드'
  | '모든 기록을 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다.'
  | '모든 기록이 삭제되었습니다.'
  | '모든 자료는 업로드 이후 24시간 뒤에 삭제됩니다'
  | '목록'
  | '목록으로'
  | '목차'
  | '문서를 분석하고 문제를 생성하려면 아래 버튼을 클릭하세요.'
  | '문의 게시판'
  | '문의 내용을 상세히 적어주세요.'
  | '문의 및 고객지원 대응'
  | '문의 및 피드백'
  | '문의 수정'
  | '문의 시: 이메일 주소, 문의 내용'
  | '문의 작성하기'
  | '문의는 아래 연락처로 접수됩니다.'
  | '문의하기'
  | '문제'
  | '문제 개수를 지정하세요'
  | '문제 로딩 중…'
  | '문제 목록'
  | '문제 생성 중...'
  | '문제 생성하기'
  | '문제 수'
  | '문제 수량: '
  | '문제 유형: '
  | '문제 유형별 기준에 맞춰 퀴즈를 생성합니다.'
  | '문제 풀기'
  | '문제 풀이: '
  | '문제를 생성하세요'
  | '미리보기 끄기'
  | '미리보기 켜기'
  | '미선택'
  | '미완료'
  | '반복 학습: '
  | '번:'
  | '범위 지정:'
  | '변경사항 로드 실패:'
  | '변함없다'
  | '보안 및 부정 이용 방지'
  | '보통 10초 ~ 30초 (문서 길이에 따라 다름)'
  | '복습 퀴즈'
  | '복습: '
  | '본 방침은 서비스 개선에 따라 변경될 수 있으며, 변경 시 공지합니다.'
  | '부산'
  | '빈칸 넣기'
  | '빈칸 채우기, OX, 객관식 중 선택'
  | '빈칸, OX, 객관식 유형을 번갈아 풀어보며 개념 이해와 기억을 균형 있게 강화하세요.'
  | '빈칸: 핵심 개념을 정확히 기억하는지 확인'
  | '빠른 시일 내에 다시 찾아뵙겠습니다.'
  | '사용자'
  | '사용자 문의에 대한 답변 내용을 입력하세요.'
  | '삭제'
  | '삭제된 퀴즈 기록은 복구할 수 없으니 신중하게 결정해주세요.'
  | '삭제하기'
  | '상세'
  | '상승한다'
  | '상태'
  | '새 문의'
  | '새 문의 작성'
  | '새 문의하기'
  | '새로고침'
  | '생성된 객관식 문제를 순서대로 풀이'
  | '생성된 문제는 학습 참고용이며, 사실관계가 100% 정확하지 않을 수 있습니다. 중요한 정보는 반드시 원본과 교차 확인하세요.'
  | '생성된 문제의 개수는 간혹 지정한 개수와 맞지 않을 수 있습니다.'
  | '생성된 퀴즈는'
  | '생성일'
  | '서버와 통신 중 문제가 발생했습니다.'
  | '서비스 운영에 필요한 범위 내에서 일부 업무를 위탁할 수 있습니다.'
  | '서비스 이용 시 자동 수집: IP 주소, 브라우저 정보, 접속 로그'
  | '서비스 점검 중입니다'
  | '서비스 제공 및 기능 개선'
  | '서비스를 만드는데 큰 도움이 됩니다.'
  | '서울'
  | '선택된 페이지 수:'
  | '선택한 답:'
  | '선택한 답안'
  | '설정'
  | '성과 확인: '
  | '소셜 계정으로 간편하게 시작하세요'
  | '소요 시간: '
  | '수정'
  | '수정 권한이 없습니다.'
  | '수정 중...'
  | '수정완료'
  | '수정하기'
  | '순수 암기나 단순 이해를 묻는 문제'
  | '슬라이드의'
  | '시행일: 2026-01-30'
  | '아직 등록된 답변이 없습니다.'
  | '아직 등록된 댓글이 없습니다.'
  | '아직 등록된 문의가 없습니다'
  | '아직 만든 퀴즈가 없습니다'
  | '안푼 문제:'
  | '알 수 없는 오류가 발생했습니다.'
  | '알 수 없다'
  | '액션'
  | '언어'
  | '언제든 이어서 풀거나 해설 다시 보기'
  | '업로드 '
  | '업로드된 문서를 AI가 분석하여 문제 생성'
  | '업로드된 파일'
  | '업로드한 파일: 퀴즈 생성 목적의 처리 과정에서 일시적으로 저장'
  | '업로드한 파일은 처리 후 24시간 이내 자동 삭제됩니다.'
  | '에러 상세 정보:'
  | '예) [전제] 물가가 오르면 화폐 가치는 떨어진다. 현재 물가가 급등했다.\n[질문] 이 경우 화폐 가치의 변화로 가장 적절한 것은?'
  | '예) 대한민국의 수도는 _______이다.'
  | '예) 지구는 태양 주위를 돈다.'
  | '오답'
  | '오답만'
  | '오답이 없습니다!'
  | '오류가 발생했습니다. 다시 시도해주세요.'
  | '옳고 그름을 판별하는 문제'
  | '완료'
  | '완료!'
  | '완료: '
  | '완료된 퀴즈만 해설을 볼 수 있습니다.'
  | '완료율'
  | '완료일'
  | '완료한 퀴즈'
  | '원칙적으로 제3자에게 제공하지 않습니다.'
  | '원하는 페이지를 지정하면 AI 퀴즈 생성시 더 좋은 퀴즈를 만들 수 있습니다.'
  | '위탁 시 관련 법령에 따라 관리·감독합니다.'
  | '유형별 풀어보기'
  | '유효한 퀴즈 정보가 없습니다. 홈으로 이동합니다.'
  | '이 기록을 삭제하시겠습니까?'
  | '이메일:'
  | '이메일: inhapj01@gmail.com'
  | '이전'
  | '입력 X'
  | '자동 저장: '
  | '자료 보호'
  | '자주 묻는 질문 (FAQ)'
  | '작성일'
  | '작성자'
  | '잠시만 기다려 주세요'
  | '적용'
  | '전체 기록 삭제 실패:'
  | '전체 또는 특정 페이지 지정'
  | '전체 문제:'
  | '전체 삭제'
  | '전체 선택'
  | '전체 해제'
  | '점'
  | '점수'
  | '점수, 소요시간 등 결과 확인'
  | '정답'
  | '정답 답안:'
  | '정말로 이 게시글을 삭제하시겠습니까?'
  | '정확하고 친절한 답변을 작성해 주세요.'
  | '제목'
  | '제목 변경 실패:'
  | '제목 수정'
  | '제목과 내용을 모두 입력해주세요.'
  | '제목은 100자 이하여야 합니다.'
  | '제목을 입력해주세요'
  | '제목이 변경되었습니다.'
  | '제출 확인'
  | '제출하기'
  | '조회'
  | '조회수'
  | '좌측 번호판으로 빠른 이동'
  | '즉시 풀고 결과 확인'
  | '지금까지 만들고 푼 퀴즈들을 확인해보세요'
  | '지원'
  | '지원 형식: '
  | '지원하는 파일'
  | '지원하지 않는 파일 형식입니다'
  | '진행 현황'
  | '진행률'
  | '참조 자료'
  | '초'
  | '총'
  | '총 퀴즈 수'
  | '총 퀴즈 수, 평균 점수 등 확인'
  | '최근 변경사항'
  | '추론, 문제 해결, 자료 해석을 요구하는 문제'
  | '취소'
  | '카카오 로그인'
  | '퀴즈 기록'
  | '퀴즈 기록 불러오기 실패:'
  | '퀴즈 기록은 로그인 후에 확인할 수 있습니다.'
  | '퀴즈 기록은 최대'
  | '퀴즈 만들기'
  | '퀴즈 생성에 실패했습니다.'
  | '퀴즈 유형'
  | '퀴즈 타입을 선택하세요'
  | '퀴즈 풀기'
  | '퀴즈를 만들어서 문제를 풀어보세요!'
  | '크기 제한'
  | '테마'
  | '테마 설정'
  | '틀린 문제 중심 재학습 가능'
  | '팁: '
  | '파일 링크가 만료되었습니다.'
  | '파일 변환 중'
  | '파일 삭제'
  | '파일 선택하기'
  | '파일 업로드 실패:'
  | '파일 업로드 중'
  | '파일 업로드 중 오류가 발생했습니다. 다시 시도해주세요.'
  | '파일 크기는 {{expr0}}MB를 초과할 수 없습니다.'
  | '파일명'
  | '파일은 상업적 목적, AI 학습 목적으로 사용되지 않습니다.'
  | '파일을 PDF로 변환하고 있어요'
  | '파일을 드래그하거나 버튼 클릭'
  | '파일을 먼저 업로드해주세요.'
  | '파일을 업로드하세요'
  | '파일을 여기에 드래그하세요'
  | '파일이 존재하지 않습니다.'
  | '페이지'
  | '페이지 범위: '
  | '페이지 범위를 올바르게 입력해주세요.'
  | '페이지 정보를 불러오는 중입니다. 잠시만 기다려주세요.'
  | '페이지를 선택해주세요.'
  | '페이지를 지정하세요'
  | '평균 점수'
  | '하락한다'
  | '학습 자료 파일'
  | '해설'
  | '해설 데이터 로딩 실패:'
  | '해설 보기'
  | '해설을 불러오는데 실패했습니다. 문제가 삭제되었을 수 있습니다.'
  | '해설이 없습니다.'
  | '현재 생성된 퀴즈가 사라집니다. 계속하시겠습니까?'
  | '현재 생성중입니다 조금만 더 기다려주세요!'
  | '현재는 pdf 파일만 지원합니다.'
  | '홈으로'
  | '확인';

/** Interpolation variables for "common" namespace keys */
declare type CommonKeyVariables = {
  '{{quizItem_userAnswer}}번': 'quizItem_userAnswer';
  '댓글 {{expr0}}건': 'expr0';
  '파일 크기는 {{expr0}}MB를 초과할 수 없습니다.': 'expr0';
};

/** Translation keys for "login-redirect" namespace */
declare type LoginRedirectKeys = '로그인 리다이렉트 실패:' | '로그인 처리 중...';

/** Translation keys for "login-select" namespace */
declare type LoginSelectKeys =
  | 'AI 기반 자동 퀴즈 생성'
  | 'AI가 만드는 나만의 퀴즈'
  | '구글 로그인'
  | '다양한 파일 형식 지원'
  | '로그인'
  | '로그인 시 서비스 이용약관에 동의하게 됩니다.'
  | '로그인이 필요합니다.'
  | '소셜 계정으로 간편하게 시작하세요'
  | '즉시 풀고 결과 확인'
  | '카카오 로그인';

/** Translation keys for "maintenance" namespace */
declare type MaintenanceKeys =
  | '더 나은 서비스를 위해 시스템을 점검하고 있습니다.'
  | '빠른 시일 내에 다시 찾아뵙겠습니다.'
  | '새로고침'
  | '서비스 점검 중입니다';

declare type MakeQuizKeys =
  | '"문제 풀기" 버튼으로'
  | '(최대'
  | '1. 빈칸 채우기로 핵심 개념을 정리하세요.'
  | '1단계: 파일 업로드'
  | '2. OX로 빠르게 개념을 점검하세요.'
  | '24시간 후 자동 삭제되며 별도로 저장, 공유되지 않습니다.'
  | '2단계: 퀴즈 옵션 설정'
  | '3. 객관식으로 개념을 응용해 보세요.'
  | '3단계: AI 문제 생성'
  | '4단계: 퀴즈 풀기'
  | '5 ~ 25개 (5개 단위)'
  | '5단계: 결과 및 해설 확인'
  | '6단계: 퀴즈 기록 관리'
  | 'AI 분석: '
  | 'AI 퀴즈 만들기 6단계 가이드'
  | 'AI 퀴즈 생성'
  | 'AI 퀴즈 활용 200% 팁'
  | 'AI 한계점:'
  | 'AI는 높은 정확도로 문서를 분석하지만, 100% 완벽하지 않을 수 있습니다. 생성된 문제는 학습 참고용이며, 중요한 정보는 반드시 원본과 교차 확인해주세요.'
  | 'OX 퀴즈'
  | 'OX: 핵심 개념의 옳고 그름을 빠르게 점검하는 문제'
  | 'PDF 로딩 중...'
  | 'PDF, PPT, Word 공부 자료로 퀴즈를 만들어 보세요. 핵심 개념을 빠르게 암기하고 시험 대비에 효과적입니다.'
  | 'Q-Asker 사용 중 궁금한 점이나 개선 아이디어가 있으시면 언제든지 알려주세요! 더 좋은'
  | 'Q-Asker 이메일 문의'
  | 'Q-Asker: PDF, PPT, Word로 무료 AI 퀴즈 생성'
  | 'Q-Asker를 신뢰할 수 있는 이유'
  | 'Q. AI가 만든 퀴즈의 정확도는 어느 정도인가요?'
  | 'Q. Q-Asker는 정말 무료인가요?'
  | 'Q. 업로드한 제 파일은 안전하게 관리되나요?'
  | 'Q. 이미지로 된 파일도 퀴즈로 만들 수 있나요?'
  | '가지고 계신 학습 자료로 AI 퀴즈를 만드는 가장 쉬운 방법을 알려드립니다.'
  | '개인정보 처리방침'
  | '객관식'
  | '객관식: 개념을 비교·분석하고 적용하는 문제'
  | '검토 기능: '
  | '결과 확인: '
  | '구글 폼 링크'
  | '구글 폼:'
  | '기록 삭제:'
  | '꼭 읽어주세요: 주의사항'
  | '나중에 다시 볼 문제에 체크 표시'
  | '네, PDF, PPT, Word 기반 AI 퀴즈 생성은 현재 완전 무료입니다. 별도의 회원가입 없이 누구나 자유롭게 이용할 수 있습니다.'
  | '네. OCR을 지원하여 스캔 본이나 사진 형태의 문서도 분석할 수 있습니다.'
  | '네. 업로드된 파일은 퀴즈 생성을 위해서만 일시적으로 사용되며, 24시간 뒤에 삭제됩니다.'
  | '네비게이션: '
  | '다른 문제 생성'
  | '다른 파일 넣기'
  | '더 많은 페이지 로딩 중... ('
  | '또는'
  | '만든 퀴즈가 퀴즈 기록에 자동 저장'
  | '명확한 문제 생성 기준'
  | '모든 자료는 업로드 이후 24시간 뒤에 삭제됩니다'
  | '문서를 분석하고 문제를 생성하려면 아래 버튼을 클릭하세요.'
  | '문의 및 피드백'
  | '문제'
  | '문제 개수를 지정하세요'
  | '문제 생성 중...'
  | '문제 생성하기'
  | '문제 수량: '
  | '문제 유형: '
  | '문제 유형별 기준에 맞춰 퀴즈를 생성합니다.'
  | '문제 풀기'
  | '문제 풀이: '
  | '문제를 생성하세요'
  | '미리보기 끄기'
  | '미리보기 켜기'
  | '반복 학습: '
  | '범위 지정:'
  | '변경사항 로드 실패:'
  | '보통 10초 ~ 30초 (문서 길이에 따라 다름)'
  | '복습 퀴즈'
  | '복습: '
  | '빈칸 넣기'
  | '빈칸 채우기, OX, 객관식 중 선택'
  | '빈칸, OX, 객관식 유형을 번갈아 풀어보며 개념 이해와 기억을 균형 있게 강화하세요.'
  | '빈칸: 핵심 개념을 정확히 기억하는지 확인'
  | '삭제된 퀴즈 기록은 복구할 수 없으니 신중하게 결정해주세요.'
  | '생성된 객관식 문제를 순서대로 풀이'
  | '생성된 문제는 학습 참고용이며, 사실관계가 100% 정확하지 않을 수 있습니다. 중요한 정보는 반드시 원본과 교차 확인하세요.'
  | '생성된 문제의 개수는 간혹 지정한 개수와 맞지 않을 수 있습니다.'
  | '서비스를 만드는데 큰 도움이 됩니다.'
  | '선택된 페이지 수:'
  | '성과 확인: '
  | '소요 시간: '
  | '언제든 이어서 풀거나 해설 다시 보기'
  | '업로드 '
  | '업로드된 문서를 AI가 분석하여 문제 생성'
  | '업로드된 파일'
  | '완료!'
  | '완료: '
  | '원하는 페이지를 지정하면 AI 퀴즈 생성시 더 좋은 퀴즈를 만들 수 있습니다.'
  | '유형별 풀어보기'
  | '이메일:'
  | '자동 저장: '
  | '자료 보호'
  | '자주 묻는 질문 (FAQ)'
  | '잠시만 기다려 주세요'
  | '적용'
  | '전체 또는 특정 페이지 지정'
  | '전체 선택'
  | '전체 해제'
  | '점수, 소요시간 등 결과 확인'
  | '제목 변경 실패:'
  | '제목이 변경되었습니다.'
  | '좌측 번호판으로 빠른 이동'
  | '지원 형식: '
  | '지원하는 파일'
  | '초'
  | '총 퀴즈 수, 평균 점수 등 확인'
  | '최근 변경사항'
  | '퀴즈 타입을 선택하세요'
  | '크기 제한'
  | '틀린 문제 중심 재학습 가능'
  | '팁: '
  | '파일 변환 중'
  | '파일 삭제'
  | '파일 선택하기'
  | '파일 업로드 중'
  | '파일은 상업적 목적, AI 학습 목적으로 사용되지 않습니다.'
  | '파일을 PDF로 변환하고 있어요'
  | '파일을 드래그하거나 버튼 클릭'
  | '파일을 업로드하세요'
  | '파일을 여기에 드래그하세요'
  | '페이지'
  | '페이지 범위: '
  | '페이지 정보를 불러오는 중입니다. 잠시만 기다려주세요.'
  | '페이지를 지정하세요'
  | '학습 자료 파일'
  | '현재 생성된 퀴즈가 사라집니다. 계속하시겠습니까?'
  | '현재 생성중입니다 조금만 더 기다려주세요!';

declare type PrivacyPolicyKeys =
  | '1. 수집하는 개인정보'
  | '2. 개인정보의 이용 목적'
  | '3. 보관 및 이용 기간'
  | '4. 제3자 제공'
  | '5. 개인정보 처리 위탁'
  | '6. 이용자 권리'
  | '7. 문의처'
  | 'Q-Asker(이하 "서비스")는 이용자의 개인정보를 소중히 보호하며 관련 법령을 준수합니다.'
  | '개인정보 열람, 정정, 삭제를 요청할 수 있습니다.'
  | '개인정보 처리방침'
  | '그 외 정보는 목적 달성 시 지체 없이 파기합니다.'
  | '다만, 법령에 따라 요청되는 경우 제공될 수 있습니다.'
  | '목차'
  | '문의 및 고객지원 대응'
  | '문의 시: 이메일 주소, 문의 내용'
  | '문의는 아래 연락처로 접수됩니다.'
  | '보안 및 부정 이용 방지'
  | '본 방침은 서비스 개선에 따라 변경될 수 있으며, 변경 시 공지합니다.'
  | '서비스 운영에 필요한 범위 내에서 일부 업무를 위탁할 수 있습니다.'
  | '서비스 이용 시 자동 수집: IP 주소, 브라우저 정보, 접속 로그'
  | '서비스 제공 및 기능 개선'
  | '시행일: 2026-01-30'
  | '업로드한 파일: 퀴즈 생성 목적의 처리 과정에서 일시적으로 저장'
  | '업로드한 파일은 처리 후 24시간 이내 자동 삭제됩니다.'
  | '원칙적으로 제3자에게 제공하지 않습니다.'
  | '위탁 시 관련 법령에 따라 관리·감독합니다.'
  | '이메일: inhapj01@gmail.com'
  | '홈으로';

declare type QuizExplanationKeys =
  | 'PDF 로딩 중...'
  | '다음'
  | '슬라이드의'
  | '오답만'
  | '이전'
  | '정답'
  | '참조 자료'
  | '파일 링크가 만료되었습니다.'
  | '파일이 존재하지 않습니다.'
  | '페이지'
  | '해설'
  | '현재는 pdf 파일만 지원합니다.'
  | '홈으로';

declare type QuizHistoryKeys =
  | '내 퀴즈 기록'
  | '다시 풀기'
  | '로그인이 필요한 서비스입니다'
  | '로그인하기'
  | '문제'
  | '미완료'
  | '삭제'
  | '상태'
  | '생성일'
  | '아직 만든 퀴즈가 없습니다'
  | '액션'
  | '완료'
  | '완료율'
  | '완료일'
  | '완료한 퀴즈'
  | '전체 삭제'
  | '점'
  | '점수'
  | '제목'
  | '지금까지 만들고 푼 퀴즈들을 확인해보세요'
  | '총 퀴즈 수'
  | '퀴즈 기록은 로그인 후에 확인할 수 있습니다.'
  | '퀴즈 만들기'
  | '퀴즈 유형'
  | '퀴즈 풀기'
  | '퀴즈를 만들어서 문제를 풀어보세요!'
  | '평균 점수';

/** Translation keys for "quiz-history-detail" namespace */
declare type QuizHistoryDetailKeys = '기록을 불러오는데 실패했습니다.' | '목록으로' | '해설 보기';

/** Translation keys for "quiz-result" namespace */
declare type QuizResultKeys = '해설 보기' | '홈으로';

declare type SolveQuizKeys =
  | '{{quizItem_userAnswer}}번'
  | '개'
  | '검토'
  | '검토할 문제:'
  | '다음'
  | '답변한 문제:'
  | '문제 로딩 중…'
  | '문제 목록'
  | '미선택'
  | '번:'
  | '선택한 답안'
  | '안푼 문제:'
  | '이전'
  | '전체 문제:'
  | '제출 확인'
  | '제출하기'
  | '진행 현황'
  | '진행률'
  | '취소'
  | '확인';

/** Interpolation variables for "solve-quiz" namespace keys */
declare type SolveQuizKeyVariables = {
  '{{quizItem_userAnswer}}번': 'quizItem_userAnswer';
};

/**
 * Maps namespace names to their translation keys
 */
declare type TranslationKeys = {
  board: BoardKeys;
  'board-detail': BoardDetailKeys;
  'board-write': BoardWriteKeys;
  common: CommonKeys;
  'login-redirect': LoginRedirectKeys;
  'login-select': LoginSelectKeys;
  maintenance: MaintenanceKeys;
  'make-quiz': MakeQuizKeys;
  'privacy-policy': PrivacyPolicyKeys;
  'quiz-explanation': QuizExplanationKeys;
  'quiz-history': QuizHistoryKeys;
  'quiz-history-detail': QuizHistoryDetailKeys;
  'quiz-result': QuizResultKeys;
  'solve-quiz': SolveQuizKeys;
};

// ============================================
// Module Augmentation
// ============================================

import type { UseTranslationReturn, UseLanguageSwitcherReturn, I18nProviderProps } from 'i18nexus';
import type { GetTranslationReturn, GetTranslationOptions } from 'i18nexus/server';

declare module 'i18nexus' {
  /**
   * Type-safe translation hook (Client Component)
   *
   * @template NS - The namespace to use
   * @param namespace - The namespace string
   * @returns Translation utilities with type-safe keys
   *
   * Note: Keys from the fallback namespace "common" are automatically included.
   *
   * @example
   * ```tsx
   * const { t } = useTranslation<"home">("home");
   * t("title");  // ✅ OK (from home namespace)
   * t("common-key");  // ✅ OK (from fallback namespace)
   * t("typo");   // ❌ Compile error!
   * ```
   */
  export function useTranslation<NS extends TranslationNamespace = TranslationNamespace>(
    namespace: NS,
  ): UseTranslationReturn<TranslationKeys[NS] | CommonKeys>;

  /**
   * Language switcher hook (Client Component)
   *
   * @returns Language switching utilities
   *
   * @example
   * ```tsx
   * const { changeLanguage, availableLanguages } = useLanguageSwitcher();
   * changeLanguage("en");  // ✅ Change to English
   * ```
   */
  export function useLanguageSwitcher(): UseLanguageSwitcherReturn;

  /**
   * I18nProvider component (Client Component)
   *
   * Provides i18n context to child components. Supports both eager and lazy loading.
   *
   * @template TTranslations - The namespace translations structure
   * @param props - Props for the I18nProvider
   * @returns React.ReactElement
   *
   * @example
   * ```tsx
   * // Lazy loading (recommended)
   * <I18nProvider
   *   loadNamespace={async (ns, lang) => {
   *     const data = await import(\`./locales/\${ns}/\${lang}.json\`);
   *     return data.default;
   *   }}
   *   fallbackNamespace="common"
   * >
   *   <App />
   * </I18nProvider>
   *
   * // Eager loading
   * <I18nProvider translations={translations}>
   *   <App />
   * </I18nProvider>
   * ```
   */
  export function I18nProvider<
    TTranslations extends Record<string, Record<string, Record<string, string>>> = Record<
      string,
      Record<string, Record<string, string>>
    >,
  >(props: I18nProviderProps<TTranslations>): React.ReactElement;

  // Individual namespace key types (for use in constants and type definitions)
  export type BoardKeys = TranslationKeys['board'];
  export type BoardDetailKeys = TranslationKeys['board-detail'];
  export type BoardWriteKeys = TranslationKeys['board-write'];
  export type CommonKeys = TranslationKeys['common'];
  export type LoginRedirectKeys = TranslationKeys['login-redirect'];
  export type LoginSelectKeys = TranslationKeys['login-select'];
  export type MaintenanceKeys = TranslationKeys['maintenance'];
  export type MakeQuizKeys = TranslationKeys['make-quiz'];
  export type PrivacyPolicyKeys = TranslationKeys['privacy-policy'];
  export type QuizExplanationKeys = TranslationKeys['quiz-explanation'];
  export type QuizHistoryKeys = TranslationKeys['quiz-history'];
  export type QuizHistoryDetailKeys = TranslationKeys['quiz-history-detail'];
  export type QuizResultKeys = TranslationKeys['quiz-result'];
  export type SolveQuizKeys = TranslationKeys['solve-quiz'];
}

declare module 'i18nexus/server' {
  /**
   * Type-safe translation function (Server Component)
   *
   * @template NS - The namespace to use
   * @param namespace - The namespace string (optional, auto-inferred)
   * @param options - Optional configuration
   * @returns Translation utilities with type-safe keys
   *
   * @example
   * ```tsx
   * const { t } = await getTranslation<"home">("home");
   * t("title");  // ✅ OK
   * t("typo");   // ❌ Compile error!
   * ```
   */
  export function getTranslation<NS extends TranslationNamespace = TranslationNamespace>(
    namespace?: NS,
    options?: GetTranslationOptions,
  ): Promise<GetTranslationReturn<NS, TranslationKeys[NS] | CommonKeys>>;
}
